hunters_camp_items = [
    "Wine Bottle (Empty)",
    "Flint and Tinder",
    "Blanket",
    "Bear Meat (1D4 Steaks)",
    "Copper Pieces (1D20)",
    "Goat (Live)",
    "Venison (Side)",
    "Chicken Meat (1D4 Pieces)",
    "Beaver Pelts (1D4)",
    "Horse (Live)",
    "Bowl",
    "Pack Mule (Live)",
    "Wine Skin (Empty)",
    "Pot",
    "Hawk Feathers (1D4)",
    "Arrows (1D4)",
    "Beaver Pelts (1D6)",
    "Candles (1D6)",
    "Raccoon Pelts (1D4)",
    "Rabbit Pelts (1D4)",
    "Short Sword",
    "Wolf Pelts (1D4)",
    "Wine Bottle (Half Full)",
    "Axe",
    "Silver Pieces (1D6)",
    "Goat Meat (1D4 Steaks)",
    "Blankets (1D4)",
    "Beaver Pelts (1D8)",
    "Oil (1 Vial)",
    "Eagle Feathers (1D6)",
    "Firewood (1D20 Logs)",
    "Raccoon Pelts (1D6)",
    "Sharpening Stone",
    "Chicken Feathers (1D20)",
    "Arrows (1D6)",
    "Dagger",
    "Club",
    "Wine Skin (Half Full)",
    "Chickens (1D4 Live)",
    "Beaver Pelts (1D10)",
    "Salt (1 Pound)",
    "Raccoon Pelts (1D8)",
    "Moose Pelts (1D4)",
    "Donkey (Live)",
    "Elk Pelts (1D4)",
    "Rabbit Pelts (1D10)",
    "Hatchet",
    "Arrows (1D8)",
    "Beaver Pelts (1D12)",
    "Blankets (1D6)",
    "Deer Pelts (1D4)",
    "Fishing Pole",
    "Wolf Pelts (1D6)",
    "Raccoon Pelts (1D10)",
    "Wine Bottle (Full)",
    "Spear",
    "Hawk Feathers (1D6)",
    "Turkey Meat (1D4 Pieces)",
    "Hammer",
    "Turkey Feathers (1D4)",
    "Lantern",
    "Tent",
    "Rabbit Pelts (1D20)",
    "Water Skin (Full)",
    "Canvas (4’x4’)",
    "Shovel",
    "Gold Pieces (1D4)",
    "Wolf Pelts (1D8)",
    "Venison (1D6 Steaks)",
    "Raccoon Pelts (1D12)",
    "Arrows (1D10)",
    "Elk Antlers",
    "Silver Pieces (1D20)",
    "Rope (50’)",
    "Tent Pegs (1D6)",
    "Fish (1D6 Fillets)",
    "Beaver Pelts (1D20)",
    "Hawk Feathers (1D8)",
    "Chicken Eggs (1D6)",
    "Fletching",
    "Blankets (1D8)",
    "Map to a Nearby Cave",
    "Long Sword",
    "Deer Antlers",
    "Lock of a Maiden’s Hair",
    "Arrows (1D12)",
    "Raccoon Pelts (1D20)",
    "Arrowheads (1D4)",
    "Wolf Pelts (1D10)",
    "Fishing Line (20’)",
    "Bear Pelts (1D4)",
    "Wine Skin (Full)",
    "Gold Pieces (1D10)",
    "Beautifully Carved Small Wooden Box (Locked)",
    "Blankets (1D10)",
    "Moose Antlers",
    "Arrows (1D20)",
    "Frying Pan",
    "Knife with an Intricately Carved Whale Bone Handle",
    "Huntsmen’s Bow (+2 Against Animals)"
]