office_items = [
    "Quill",
    "Ink jar (half full)",
    "Blank parchments (3)",
    "Platinum necklace (100gp)",
    "Blank velum (5)",
    "Signet ring",
    "Candles (2)",
    "Gold torc (25pg)",
    "Wax (3 cubes)",
    "Iron arm ring (10gp)",
    "Ledger",
    "Diary",
    "Note",
    "Gems (1D4, 25gp each)",
    "Secret message",
    "Gold pieces (1D6)",
    "String (3’)",
    "Copper pieces (1D8)",
    "Blank paper (8)",
    "Large book",
    "Gold pieces (1D10)",
    "Straightedge",
    "Small book",
    "Silver pieces (1D6)",
    "Iron circlet (15gp)",
    "Leather pouch",
    "Silk vest (50gp)",
    "Satin pouch",
    "Governmental documents",
    "Silk pouch",
    "Iron torc (15pg)",
    "Gold arm ring (75pg)",
    "Ink blotter",
    "Scribe’s knife",
    "Polished pebbles (6)",
    "Iron statuette (5gp)",
    "Silver bracelet (50gp)",
    "Satin vest (50gp)",
    "Iron bracelet (10gp)",
    "Silver pieces (1D12)",
    "Gold bracelet (15gp)",
    "Dagger",
    "Jeweled dagger (+1 to hit)",
    "Silver amulet (25gp)",
    "Letters (5)",
    "Sealed letter",
    "Tinder box",
    "Copper pieces (1D8)",
    "Wool scarf",
    "Satin scarf",
    "Gold statuette (75pg)",
    "Silk scarf",
    "Leather gloves",
    "Smoking pipe",
    "Satin gloves",
    "Short sword",
    "Silk gloves",
    "Gems (1D6)",
    "Silver arm ring (35gp)",
    "Wool cloak",
    "Spyglass",
    "Satin cloak (80gp)",
    "Flask of oil",
    "Silk cloak (100gp)",
    "Blank volume",
    "Writing pigments (4)",
    "Gold amulet (50gp)",
    "Antique book (30gp)",
    "Map",
    "Protractor",
    "Silver statuette (25gp)",
    "Jeweled short sword (+1 to hit)",
    "Wool vest",
    "Badge of office (symbol on leather)",
    "Cargo lists",
    "Caravan timetables",
    "Silver circlet (30gp)",
    "Supply manifest",
    "Silver pieces (1D10)",
    "Iron ring (5gp)",
    "Whetstone",
    "Silver ring (20gp)",
    "Crystal",
    "Gold ring (30gp)",
    "Magnifying glass",
    "Gold pieces (1D12)",
    "Monocle",
    "Copper ring (5gp)",
    "Long Bottom Leaf (8 uses)",
    "Star chart",
    "Platinum ring (30gp)",
    "Gold circlet (40gp)",
    "Secret map",
    "Bead necklace (10gp)",
    "Silver torc (50gp)",
    "Spectacles",
    "Silver necklace (60gp)",
    "Platinum pieces (1D12)",
    "Gold necklace (90gp)",
    "Gems (1D12, 50gp each)"
]