wizard_chamber_items = [
    "Canary in a cage",
    "Short sword",
    "Chicken eggs (6)",
    "Bat in a cage",
    "Spyglass",
    "Tome of ancient history",
    "Star Chart",
    "Ink (2 jars)",
    "Frog in a glass bowl",
    "Crystal shard (6”)",
    "Rat in a cage",
    "Various personal letters",
    "Map to a legendary library",
    "Parchment (2, blank)",
    "Robin eggs (2)",
    "Glass vial",
    "Healing potion",
    "Globe",
    "Small warrior fifi gurine",
    "Quartz (2”)",
    "Candle (2)",
    "Illustrated book about birds",
    "Crystal ball",
    "Quill",
    "Gold pieces (1D20)",
    "Smoking Pipe",
    "Various roots",
    "Book of ancient runes",
    "Poison (2 doses)",
    "Finch in a cage",
    "Owl (stuffed)",
    "Wicks (5)",
    "Illustrated book about dragons",
    "Hourglass",
    "Diary",
    "Fossilized shark teeth (4)",
    "Bee preserved in alcohol",
    "Moss (dried)",
    "Bone powder",
    "Scribe’s knife",
    "Oil (1 vial)",
    "Mushrooms growing in pot",
    "Lizard in a cage",
    "Bottle cork (3)",
    "White mice in a cage (7)",
    "Wax (3 blocks)",
    "Frog legs (8, dried)",
    "Packet of seeds (35)",
    "Snake preserved in alcohol",
    "Journal book (blank)",
    "Butterflfl y net",
    "Illustrated book about fish",
    "Vellum (4, blank)",
    "Glass bottle",
    "Ink blotter",
    "Silver pieces (1D100)",
    "Book of magical theory",
    "Dagger",
    "Spider eggs in a jar (15)",
    "Book of mythical beasts",
    "Lamp",
    "Book of potions",
    "Collection of ancient scrolls",
    "Small velvet bag",
    "Small ruby",
    "Hazelnuts (12)",
    "Human skull",
    "Copper tubing (3’)",
    "Book of folklore",
    "Tome of recent history",
    "Snake venom in a jar",
    "Collection of leafs (dried)",
    "Book of herbs",
    "Small wooden spheres (6)",
    "Collection of small fossils",
    "Alligator (stuffed)",
    "Bat wings (8, dried)",
    "Board with various insects pinned",
    "Toadstools (7, dried)",
    "Hat",
    "Illustrated book about plants",
    "Salamander in a glass bowl",
    "Collection of odd rocks",
    "Signet ring",
    "Small leather pouch",
    "Longbottom leaf (9, dried)",
    "Tome of magic history",
    "Small wooden chest (empty)",
    "Cay tablet with inscription",
    "Book of astrology",
    "Snake eggs preserved in alcohol",
    "Healing potion (2)",
    "Monkey (stuffed)",
    "Book of spirits and apparitions",
    "Book of alchemy",
    "Small mystic symbol",
    "Ancient vellum manuscript",
    "Telescope",
    "Staff",
    "Spell book"
]