mountain_encounters_list = [
    'Bear',
    'Goblins (1D4)',
    'Crevasse',
    'Frozen body',
    'Mountain goat',
    'Bear trap',
    'Avalanche',
    'Wolf',
    'Campfire (still warm)',
    'Bear tracks',
    'Orcs (1D4)',
    'Distant smoke',
    'Rusted chest',
    'Traveling doctor',
    'Bandits (1D4)',
    'Ghost',
    'Bear cubs (1D4)',
    'Band of dwarves (1D8)',
    'Sheer cliff',
    'Bounty hunters (1D6)',
    'Orc raiding party (1D6)',
    'Bear droppings',
    'Ice wall',
    'Orphan',
    'Tomb',
    'Lost hunter',
    'Strange flowers',
    'Thick fog',
    'Saddled horse',
    'Wolves (1D4)',
    'Wild donkeys (1D6)',
    'Frozen pond',
    'Bandits (1D6)',
    'Poachers (1D4)',
    'Troll',
    'Bandits (1D8)',
    'Messenger',
    'Bandits (1D10)',
    'Hunter’s stack',
    'Temple',
    'Adventuring party (1D8)',
    'Goblins (1D20)',
    'Logging camp',
    'Lost coin purse',
    'Burning wagon',
    'Fox',
    'No trespassing sign',
    'Merchant caravan (1D12 wagons)',
    'Wolves (1D6)',
    'Bandits (1D12)',
    'Circling vultures',
    'Old path',
    'Nobles (1D4)',
    'Traveling bard',
    'Mountain goats (1D6)',
    'Abandoned campfire',
    'Shrine',
    'Exposed ore vein',
    'Rabbits (1D6)',
    'Snow cave',
    'Rockslide',
    'Foxes (1D4)',
    'Dead bear',
    'Elven outcast',
    'Wolves (1D8)',
    'Broken statue',
    'Abandoned food cart',
    'Injured hunter',
    'Dead orc war party',
    'Orcs (1D20)',
    'Mineshaft',
    'Old abandoned fortress',
    'Grove',
    'Mudslide',
    'Snowman',
    'Bears (1D4)',
    'Bear cave',
    'Merchant caravan (1D20 wagons)',
    'Traveling cleric',
    'Trading outpost',
    'Hunters (1D12)',
    'Mercenary camp',
    'Traveling merchant',
    'Orcs (1D12)',
    'Stream',
    'Eagle’s nest',
    'Wolves (1D10)',
    'Inn',
    'Mountain lion',
    'Wandering Wizard',
    'Burnt down building',
    'Blizzard',
    'Mountain giant',
    'Wolves (1D12)',
    'Bandits (1D20)',
    'Dire wolf',
    'Trolls (1D4)',
    'Wolves (1D20)',
    'Dragon',
    'Frost giant'
]
