seafaring_encounters_list = [
    "A Pod of Whales (1D4)",
    "Ghost Ship",
    "A Flag from a Legendary Pirate Ship",
    "Slave Ship",
    "Raft (1D4 survivors)",
    "Pirate Ship",
    "A Pod of Whales (1D6)",
    "Merchant Ship",
    "Jetsam (1D20 salvageable items)",
    "Giant Squid",
    "Warship",
    "Slave Ship Fleet (1D4)",
    "Mermaid",
    "Uncharted Island (megaliths)",
    "A Pod of Whales (1D8)",
    "Merchant Fleet (1D4)",
    "Pirate Fleet (1D4)",
    "Giant Octopus",
    "Lagan Marked with a Cork",
    "A Pod of Whales (1D10)",
    "Derelict Ship",
    "Slave Ship Fleet (1D6)",
    "Board with “The Lady Luck” on it",
    "Merchant Fleet (1D6)",
    "Flotsam (1D20 salvageable items)",
    "Pirate Fleet (1D6)",
    "A Message in a Bottle",
    "A Pod of Whales (1D12)",
    "Uncharted Island (lone castaway)",
    "Warship Fleet (1D4)",
    "Doldrums",
    "Slave Ship Fleet (1D8)",
    "Lost Ship",
    "Merchant Fleet (1D8)",
    "A buoy with a message",
    "Pirate Fleet (1D8)",
    "Uncharted Island (village)",
    "A Pod of Whales (1D20)",
    "Raft (lone survivor)",
    "Merchant Fleet (1D10)",
    "Raft (1D6 dead bodies)",
    "Whirlpool",
    "Slave Ship Fleet (1D10)",
    "Shooting Star (good omen)",
    "Mermaids (1D4)",
    "Lifeboat (empty)",
    "Warship Fleet (1D6)",
    "Green Gaseous Cloud",
    "Plesiosaurus",
    "Pirate Fleet (1D10)",
    "Dragon Turtle",
    "Ship from Exotic Locale",
    "Merchant Fleet (1D12)",
    "Flotsam (no salvageable items)",
    "A Pod of Whales (1D100)",
    "Jetsam (1D100 salvageable items)",
    "Warship Fleet (1D8)",
    "Sargassum Seaweed",
    "Pirate Fleet (1D12)",
    "Sea Hag",
    "Uncharted Island (secluded lagoon)",
    "Slave Ship Fleet (1D12)",
    "Lifeboat (1D4 survivors)",
    "Bird Sign (ill omen)",
    "Uncharted Island (ruins)",
    "Shark Feeding Frenzy",
    "Warship Fleet (1D10)",
    "Barrel of Rum",
    "A Bottle with a Navigation Chart",
    "Red Gaseous Cloud",
    "Lagan Marked with a Buoy",
    "Merchant Ship (sinking, crew abandoning)",
    "Merchant Fleet (1D20)",
    "Strong Winds",
    "Raft (1D8 survivors)",
    "Barrels of Rum (1D8)",
    "A Coffin",
    "Pirate Ship (entire crew dead)",
    "Uncharted Island (shipwreck 1D20 survivors)",
    "Pirate Fleet (1D20)",
    "Water Spout",
    "Flotsam (1D100 salvageable items)",
    "Raft (single dead body)",
    "Warship Fleet (1D12)",
    "Lifeboat (engraved pocket watch inside)",
    "Storm",
    "Slave Ship Fleet (1D20)",
    "Red Tide",
    "Island (penal colony)",
    "Uncharted Island (cave)",
    "Raft (a chest)",
    "Talking Fish",
    "Uncharted Island (pirate base)",
    "Capsized Ship",
    "Raft (1D8 dead bodies)",
    "Giant White Whale",
    "Warship Fleet (1D20)",
    "Hurricane",
    "Treasure Ship",
    "Kraken"
]