fatal_curses_list = [
    "Curse of Lingering Doom: The character is marked for doom, but the specific nature of their demise remains uncertain. They have one year to find a way to avert it.",
    "Eldritch Possession: The character is periodically possessed by an eldritch entity, losing control during these episodes but retaining their self-awareness. They must seek a way to sever this connection.",
    "Soulbound Anguish: The character's soul is bound to an eternal tormentor, causing them severe pain at unpredictable intervals. They must find a way to appease or negotiate with this entity.",
    "Curse of Unrelenting Despair: The character experiences waves of despair and suicidal thoughts but has the opportunity to seek counseling or magical assistance to manage their mental anguish.",
    "Marked by Calamity: The character attracts catastrophic events, but they can mitigate the damage by making choices and taking actions that safeguard themselves and others.",
    "Eldritch Corruption: The character's body begins to mutate, and they must find a way to halt or control these changes before they become a monstrous abomination.",
    "Soulbound Isolation: The character's soul is bound to a desolate plane, causing feelings of emptiness and loneliness. They can seek out companionship or purpose to mitigate these effects.",
    "Curse of Incessant Torment: The character suffers bouts of agonizing pain, but they can temporarily suppress these episodes with extraordinary effort or by finding a cure.",
    "Eldritch Domination: The character is influenced by eldritch beings but retains moments of lucidity. They must find a way to regain control over their actions.",
    "Soulbound Trial: The character's soul is condemned but can potentially earn redemption through heroic deeds or selfless acts.",
    "Curse of the Abyssal Rift: The character's presence opens a rift, but they can learn to control and even close it with the right knowledge and magic.",
    "Marked by Oblivion: The character's touch causes objects to decay, but they can learn to reverse this effect with time and practice.",
    "Eldritch Plague: The character carries an eldritch plague, but they can seek a cure or find ways to contain its spread.",
    "Soulbound Exile: The character is bound to a desolate realm but can seek a way back to the material plane through a quest or powerful magic.",
    "Curse of Perpetual Nightmares: The character suffers from nightmares but can confront and overcome them through therapy or magical means.",
    "Marked by Voidfire: The character can control the dark flames they emit, learning to use them as a weapon or tool.",
    "Eldritch Reckoning: The character's actions have consequences, but they can work to mitigate these consequences through heroic acts.",
    "Soulbound Transformation: The character's soul faces transformation but can seek a way to harness this change for their benefit.",
    "Curse of the Everlasting Void: The character is slowly consumed by the void, but they can find ways to slow or halt the process.",
    "Marked by Cosmic Chaos: The character can learn to harness the chaotic events they attract, using them strategically.",
    "Curse of Haunting Visions: The character experiences haunting visions of doom, but they can seek guidance or knowledge to interpret and potentially avert these events.",
    "Eldritch Reflections: The character's reflection reveals eldritch horrors, but they can learn to control and conceal these unsettling images.",
    "Soulbound Taint: The character's soul carries a taint, causing mistrust among those they meet. They can earn trust through heroic actions and selflessness.",
    "Curse of the Eternal Echo: The character's words and actions echo ominously, but they can find ways to harness this effect for strategic advantage.",
    "Marked by Ethereal Shadows: The character is followed by eerie, shadowy figures, but they can potentially learn to communicate with or influence these entities.",
    "Eldritch Relic: The character is bound to an eldritch artifact with its own agenda, but they can seek to understand and control the relic's powers.",
    "Soulbound Atonement: The character's soul is bound to a force seeking redemption, and they must embark on a quest to fulfill this mission.",
    "Curse of Unholy Allure: The character radiates an aura of darkness, drawing sinister creatures toward them, but they can learn to repel or control these entities.",
    "Marked by Cursed Luck: The character's luck is both a blessing and a curse, but they can learn to manipulate or mitigate its unpredictable effects.",
    "Eldritch Metamorphosis: The character's body slowly mutates, but they can uncover rituals or knowledge that allow them to control or harness these changes.",
    "Soulbound Balance: The character's soul is bound to a cosmic scale, causing them to experience extreme highs and lows. They can strive to find equilibrium.",
    "Curse of the Astral Chasm: The character's presence creates rifts in reality, but they can learn to control and stabilize these rifts.",
    "Marked by Eerie Silence: The character is followed by an unnatural silence, but they can discover ways to break this silence for strategic advantage.",
    "Eldritch Veil: The character becomes partially intangible, but they can learn to solidify at will, granting them unique abilities.",
    "Soulbound Aberration: The character's soul is intertwined with an aberrant entity, but they can seek to understand and potentially negotiate with this entity.",
    "Curse of Unending Shadows: The character is followed by a legion of shadows, but they can learn to command and direct these shadows as allies.",
    "Marked by Shattered Realities: The character's presence occasionally distorts reality, but they can seek to control and manipulate these distortions.",
    "Eldritch Temptation: The character is drawn to forbidden knowledge, but they can strive to resist its allure and avoid its corrupting influence.",
    "Soulbound Embrace: The character's soul is bound to a powerful entity, but they can work to align their goals and find mutual benefit.",
    "Curse of Relentless Pursuit: The character is hunted by a relentless force, but they can seek knowledge or allies to help evade or confront their pursuer.",
    "Curse of Echoing Guilt: The character hears echoing whispers of past wrongs, but they can seek redemption through acts of kindness and selflessness.",
    "Eldritch Enigma: The character becomes an enigma to others, but they can learn to use their mysterious nature to their advantage.",
    "Soulbound Shapeshift: The character's soul is bound to a shape-shifting entity, granting them the ability to take on different forms, but they must learn to control these transformations.",
    "Curse of Timeless Reflection: The character's reflection in mirrors shows their true, monstrous form, but they can find ways to conceal or transform this reflection.",
    "Marked by Phantasmal Echoes: The character's presence occasionally triggers vivid phantasmal echoes of past events, which they can learn to use for strategic insight.",
    "Eldritch Nexus: The character becomes a nexus of eldritch energies, attracting magical phenomena, but they can learn to channel and control these energies.",
    "Soulbound Redemption: The character's soul is bound to a being seeking redemption, leading them on a quest to right past wrongs.",
    "Curse of Ephemeral Shadows: The character casts no shadow, making them seem ethereal, but they can learn to use this effect to become invisible.",
    "Marked by Unseen Hands: The character is subtly manipulated by unseen forces, but they can work to resist this influence and regain control.",
    "Eldritch Resonance: The character's presence resonates with eldritch vibrations, allowing them to detect magical auras, but they must learn to harness this ability.",
    "Soulbound Alacrity: The character's soul is bound to a restless spirit, granting them incredible speed but also a craving for constant movement.",
    "Curse of Fading Memories: The character's memories slowly fade, but they can seek out mages or artifacts to preserve or restore their recollections.",
    "Marked by Dissonance: The character's existence disrupts magical harmony, causing wild surges in spells, but they can learn to control and direct these surges.",
    "Eldritch Labyrinth: The character is trapped in a shifting, otherworldly labyrinth whenever they sleep but can work to navigate its depths and discover its secrets.",
    "Soulbound Vigilance: The character's soul is bound to an ancient sentinel, granting them heightened senses but also a compulsion to protect sacred sites.",
    "Curse of Unseen Threads: The character's life is tied to invisible threads, and they can sense when someone touches these threads, allowing them to detect hidden dangers.",
    "Marked by Astral Veins: The character's presence reveals the veins of the astral plane, enabling them to access alternate dimensions but also attracting extraplanar entities.",
    "Eldritch Connection: The character forms a mysterious connection with eldritch beings, allowing them to communicate with these entities but also making them a target for their desires.",
    "Soulbound Echo: The character's soul echoes through time, enabling them to glimpse glimpses of the past and future but also burdening them with disjointed visions.",
    "Curse of Eclipsed Fate: The character's fate is shrouded in darkness, but they can seek knowledge or rituals to unveil their destiny and influence its course.",
    "Eldritch Ward: The character is marked by protective runes of an unknown eldritch origin, granting them resistance to certain magical effects but attracting those who seek the runes' power.",
    "Soulbound Echoes: The character's soul carries echoes of past lives, allowing them to access the skills and knowledge of previous incarnations but also causing identity confusion.",
    "Curse of Ethereal Chains: The character is bound by ethereal chains, granting them telekinetic abilities but also causing physical exhaustion when overused.",
    "Marked by Sublime Music: The character is followed by ethereal music, which can inspire or manipulate those who hear it but also draw the attention of supernatural entities.",
    "Eldritch Rejuvenation: The character's body can momentarily heal from any injury, but this process causes them immense pain, and they must learn to control this power.",
    "Soulbound Compassion: The character's soul is bound to a compassionate entity, causing them to feel overwhelming empathy but also the need to help those in distress.",
    "Curse of Chronal Shifting: The character randomly shifts through time, experiencing brief moments from their past and future, which can provide insights or cause disorientation.",
    "Marked by Arcane Anomalies: The character is surrounded by arcane anomalies, granting them unpredictable magical effects but also making them a target for those who seek arcane knowledge.",
    "Eldritch Whispers: The character hears constant eldritch whispers that convey cryptic information but also induce paranoia.",
    "Soulbound Transformation: The character's soul is bound to an entity that grants them the ability to transform into powerful creatures but at the cost of their own identity.",
    "Curse of Eternal Regret: The character is haunted by past mistakes, which drive them to make amends but also cause immense emotional turmoil.",
    "Marked by Cosmic Serenity: The character exudes an aura of cosmic calmness, allowing them to pacify conflicts but also attracting those who wish to exploit their influence.",
    "Eldritch Malleability: The character's body becomes malleable, allowing them to change their physical form but also making them vulnerable to shape-shifting creatures.",
    "Soulbound Shadow: The character's soul is bound to a shadowy entity, granting them control over shadows and darkness but also a growing affinity for malevolent acts.",
    "Curse of Disappearing Acts: The character occasionally disappears from existence for brief moments, but they must learn to control this phenomenon to avoid being lost forever.",
    "Marked by Celestial Discord: The character's presence disrupts celestial harmony, causing celestial beings to mistrust them but also granting them resistance to celestial magic.",
    "Eldritch Wandering: The character occasionally experiences uncontrollable teleportation to random locations, which can provide shortcuts or lead to dangerous situations.",
    "Soulbound Duality: The character's soul is bound to two conflicting entities, granting them access to both light and dark powers but also causing inner turmoil.",
    "Curse of Perpetual Enigma: The character is an enigma to others, making it difficult for them to form lasting bonds but also granting them the ability to conceal their true intentions.",
    "Marked by Arcane Crystals: The character is marked by radiant arcane crystals that can be harnessed for powerful magic but also attract those who seek to steal their essence.",
    "Eldritch Tendrils: The character's touch sends forth eldritch tendrils that can manipulate objects at a distance but also expose them to the influence of otherworldly entities.",
    "Soulbound Luminance: The character's soul is bound to an ethereal light, granting them the power to radiate blinding brilliance but also making them a target for creatures of darkness.",
    "Curse of Cosmic Echoes: The character is occasionally struck by cosmic echoes that grant glimpses of otherworldly knowledge but also induce madness.",
    "Marked by Elemental Imbalance: The character is marked by elemental imbalances that grant them control over natural forces but also make them vulnerable to elemental extremes.",
    "Eldritch Warding: The character is protected by an eldritch ward that repels malevolent beings but also isolates them from the world.",
    "Soulbound Empathy: The character's soul is bound to the emotions of others, granting them insight into others' feelings but also causing them to absorb others' pain.",
    "Curse of Shifting Realities: The character occasionally shifts into alternate realities, which can provide unique insights or create hazardous situations.",
    "Marked by Cosmic Alacrity: The character's movements are quickened by cosmic forces, granting them extraordinary speed but also making it challenging to control their actions.",
    "Eldritch Charisma: The character's presence is charismatic and hypnotic, allowing them to sway the minds of others but also attracting those who seek to exploit their charm.",
    "Soulbound Restraint: The character's soul is bound to an entity that suppresses their emotions, granting them stoic resolve but also stifling their empathy.",
    "Curse of Eternal Vigilance: The character is haunted by visions of impending danger, which grant them heightened awareness but also induce paranoia.",
    "Marked by Astral Insights: The character is marked by celestial insights, granting them profound knowledge but also exposing them to celestial scrutiny.",
    "Eldritch Weaving: The character can weave eldritch energies to craft intricate spells, but these spells often have unintended consequences.",
    "Soulbound Tempest: The character's soul is bound to a stormy entity, granting them control over weather patterns but also making them susceptible to emotional turmoil.",
    "Curse of Lingering Shadows: The character's shadow becomes sentient and can act independently, sometimes aiding or sabotaging them.",
    "Marked by Unseen Silence: The character is followed by an aura of silence, which can muffle sounds or shield them from detection but also disrupt communication.",
    "Eldritch Aversion: The character is naturally repelled by eldritch beings, who find it challenging to approach them but are also drawn to their unique essence.",
    "Soulbound Dual Nature: The character's soul is bound to two contrasting entities, granting them access to conflicting abilities and desires.",
    "Curse of Eternal Turmoil: The character is plagued by inner turmoil, which drives them to seek balance or succumb to chaotic tendencies.",
    "Marked by Celestial Ascent: The character is marked for a celestial ascent, which grants them divine insights but also attracts divine beings seeking to guide or test them.",
]