major_curses_list = [
    "Haunted Whispers: The character is haunted by eerie whispers that only they can hear, making it difficult to focus, imposing disadvantage on Wisdom (Perception) checks.",
    "Dark Stalker: The character is constantly followed by a shadowy creature, unsettling others around them, imposing disadvantage on Charisma checks when interacting with non-hostile NPCs.",
    "Monstrous Gaze: People perceive the character as a monstrous entity, making social interactions challenging and imposing disadvantage on Charisma checks when dealing with strangers.",
    "Initiative Slump: The character always acts last in combat, suffering a -2 penalty to their initiative rolls.",
    "Armored Burden: The character finds it difficult to wear armor, resulting in a -2 penalty to their Armor Class when wearing any type of armor.",
    "Berserker's Wrath: In moments of intense anger, the character goes into a berserker rage, attacking the nearest creature, ally or foe.",
    "Sensory Dullness: The character loses one of their senses (sight, hearing, taste, smell, or touch), making daily life and combat more challenging.",
    "Addiction to Shadows: The character becomes addicted to consuming shadowy substances, suffering from withdrawal if they don't indulge.",
    "Beastly Transformation: The character occasionally transforms into a harmless animal, potentially leading to awkward situations.",
    "Summoning Curse: Whenever the character rolls a natural 1 on an attack roll, a chaotic or harmful entity is inadvertently summoned.",
    "Mutagenic Effects: The character experiences random physical mutations, which can have both positive and negative effects on their abilities.",
    "Intrusive Thoughts: The character is plagued by strange and disturbing thoughts, making it difficult to concentrate and imposing disadvantage on Intelligence checks.",
    "Cursed Hunger: The character develops an insatiable appetite for strange or unsavory foods, potentially leading to cannibalistic tendencies.",
    "Monster Appendage: The character grows a monstrous appendage (claw, tentacle, etc.) that can be both a benefit and a hindrance.",
    "Magic Seizures: The character is granted access to magical spells but suffers from unpredictable, adverse effects each time they cast a spell.",
    "Critical Misfortune: Whenever the character rolls a natural 1 on certain checks (e.g., saving throws), something exceptionally bad happens beyond the normal failure.",
    "Widespread Fear: People are inexplicably afraid of the character, making social interactions highly challenging and imposing disadvantage on all Charisma checks.",
    "Ghostly Apparitions: The character is followed by ghostly figures, which occasionally distract them, imposing disadvantage on Wisdom checks.",
    "Cursed Limb: One of the character's limbs becomes cursed, making it difficult to use in certain situations.",
    "Chronic Transformations: The character frequently changes into bizarre and uncontrollable forms, affecting their abilities and social standing.",
    "Inescapable Bad Luck: The character constantly experiences a streak of bad luck, suffering a -2 penalty to all skill checks and saving throws.",
    "Spectral Retribution: When the character damages another creature, a spectral force retaliates, causing the character to take half the damage they dealt.",
    "Inversion Curse: The character's moral compass becomes inverted, leading to questionable decision-making and potentially alienating allies.",
    "Maddening Whispers: The character hears maddening whispers, causing erratic behavior and imposing disadvantage on Wisdom saving throws.",
    "Fiendish Attraction: The character is irresistibly drawn to malevolent beings, making it difficult to resist their influence and imposing disadvantage on saving throws against charm effects from such beings.",
    "Ancestral Curses: The character inherits curses from their ancestors, which randomly manifest as inconvenient afflictions.",
    "Fleeting Memories: The character's memories fade quickly, making it challenging to recall important information and imposing disadvantage on Intelligence checks related to memory.",
    "Magnetic Aura: The character emits a strange aura that attracts metallic objects, causing them to frequently become entangled or immobilized.",
    "Elemental Instability: The character's presence causes fluctuations in elemental forces, leading to erratic weather patterns and other unpredictable natural phenomena.",
    "Soul Siphon: The character's presence drains the energy of those nearby, causing fatigue and exhaustion to allies within 30 feet.",
    "Plagued Dreams: The character is tormented by disturbing nightmares, leaving them sleep-deprived and imposing disadvantage on Constitution saving throws to resist exhaustion.",
    "Reality Phasing: The character occasionally phases partially out of the material plane, making them temporarily immune to damage but unable to interact with their surroundings.",
    "Hexed Items: All magical items the character carries occasionally malfunction, causing unintended side effects.",
    "Temporal Distortion: The character experiences unpredictable shifts in time, causing them to age or de-age temporarily.",
    "Ephemeral Form: The character occasionally becomes intangible, making it difficult to interact with the physical world.",
    "Summoner's Curse: The character is perpetually followed by summoned creatures, which occasionally cause chaos and destruction.",
    "Bloodlust: The character experiences uncontrollable urges to engage in combat, potentially leading to violent outbursts in inappropriate situations.",
    "Shared Pains: The character feels the physical pain of any creature they harm, causing them to hesitate in combat.",
    "Specter's Touch: The character can interact with ghosts and spirits but is occasionally possessed by them, leading to erratic behavior.",
    "Hexed Armor: The character's armor becomes hexed, randomly imposing penalties on their attacks or abilities.",
    "Phantom Ailments: The character suffers from a variety of phantom ailments, causing them to temporarily lose the use of limbs or senses.",
    "Magical Mute: The character is struck mute whenever they attempt to cast a spell, making verbal spells impossible.",
    "Misdirection: The character is prone to becoming hopelessly lost, even in familiar locations.",
    "Ectoplasmic Residue: The character leaves traces of ectoplasm wherever they go, causing suspicion and fear among those who encounter it.",
    "Dreamwalker's Curse: The character becomes a conduit for malevolent entities from the dream realm, occasionally bringing their nightmares to life.",
    "Empathic Drain: The character drains the emotions of those nearby, causing friends and allies to become emotionally distant.",
    "Magic Burn: The character takes damage each time they cast a spell, causing physical harm in exchange for magical power.",
    "Poltergeist Tendencies: The character's presence occasionally causes objects to levitate or move of their own accord, leading to disturbances.",
    "Jinxed Luck: The character is followed by a constant string of bad luck, leading to mishaps and failures in their daily life.",
    "Inversion of Senses: The character's senses occasionally become inverted, causing them to perceive the world in strange and disorienting ways.",
    "Magnetic Attraction: The character is drawn to metallic objects, making it difficult to avoid triggering traps or alarms.",
    "Astral Disconnection: The character experiences moments of astral disconnection, causing them to briefly lose consciousness.",
    "Voracious Hunger: The character develops an insatiable appetite for bizarre or inedible substances, occasionally causing them to consume harmful materials.",
    "Beastly Possession: The character becomes occasionally possessed by a wild animal spirit, leading to uncontrollable behavior.",
    "Mutation Outbreak: The character's body frequently mutates, causing sudden and unpredictable physical changes.",
    "Pervasive Fear: The character's presence causes intense fear in others, making allies occasionally unwilling to approach or help them.",
    "Reality Distortion: The character's mere presence causes minor distortions in the fabric of reality, leading to bizarre and inconvenient phenomena.",
    "Celestial Condemnation: The character is plagued by visions of celestial beings condemning them for past actions, leading to mental distress.",
    "Haunted Possessions: All items the character carries are occasionally possessed by mischievous spirits, causing them to behave erratically.",
    "Poltergeist Echo: The character's emotions occasionally manifest as physical phenomena, causing disturbances in their surroundings.",
    "Hexed Curses: The character becomes the target of hexes from otherworldly entities, leading to unpredictable curses and misfortunes.",
    "Corporeal Instability: The character's body occasionally becomes semi-transparent, making it difficult to interact with the physical world.",
    "Elemental Infection: The character occasionally emits elemental energies, leading to uncontrollable elemental effects in their vicinity.",
    "Psychic Feedback: The character is plagued by psychic feedback from their surroundings, leading to erratic behavior.",
    "Temporal Jumps: The character occasionally jumps forward or backward in time, experiencing disjointed memories and events.",
    "Enigmatic Charms: The character is occasionally charming and likable but unpredictable in their behavior.",
    "Chaos Aura: The character emits an aura of chaos, causing unpredictable events to occur nearby.",
    "Spectral Passage: The character occasionally phases through solid objects, making it difficult to maintain a physical presence.",
    "Cursed Paralysis: The character becomes temporarily paralyzed at unpredictable moments.",
    "Phantom Influence: The character is influenced by malevolent phantoms, leading to erratic and destructive behavior.",
    "Hexed Affections: The character becomes the target of love or hatred from supernatural entities, leading to unpredictable relationships and interactions.",
    "Monstrous Descent: The character occasionally transforms into a monstrous form, making social interactions difficult.",
    "Temporal Displacement: The character experiences shifts in time, causing them to age or de-age temporarily.",
    "Ephemeral Manifestation: The character occasionally disappears from the material plane, making them difficult to perceive or interact with.",
    "Summoner's Woe: The character is perpetually followed by summoned creatures, which occasionally disobey commands and act independently.",
    "Vampiric Tendencies: The character develops vampiric cravings for blood, causing distress in social situations.",
    "Nightmarish Phantasms: The character is plagued by vivid and unsettling nightmares, leading to sleep disturbances and exhaustion.",
    "Shadow Infestation: The character is followed by shadowy entities, causing paranoia and fear in those around them.",
    "Temporal Eclipses: The character experiences temporary temporal eclipses, causing them to lose track of time and potentially miss important events.",
    "Unstable Illusions: The character can cast illusions but suffers from unstable magic, causing illusions to frequently dissipate.",
    "Cursed Aura: The character emits an aura of misfortune, leading to frequent accidents and mishaps.",
    "Hexed Visions: The character is plagued by disturbing visions, causing mental distress and erratic behavior.",
    "Spectral Lure: The character is irresistibly drawn to supernatural entities, making it difficult to resist their influence.",
    "Phantom Parasite: The character is occasionally possessed by malevolent entities, causing erratic and destructive behavior.",
    "Hexed Protection: The character's protective spells occasionally malfunction, causing unintended side effects.",
    "Psychic Turbulence: The character experiences frequent psychic turbulence, leading to erratic behavior and thoughts.",
    "Temporal Tremors: The character suffers from temporal tremors, causing them to briefly lose consciousness.",
    "Cursed Hunger: The character develops an insatiable appetite for strange or unsavory foods, potentially leading to cannibalistic tendencies.",
    "Monster's Gaze: People perceive the character as a monstrous entity, making social interactions challenging and imposing disadvantage on Charisma checks when dealing with strangers.",
    "Initiative Slump: The character always acts last in combat, suffering a -2 penalty to their initiative rolls.",
    "Armored Burden: The character finds it difficult to wear armor, resulting in a -2 penalty to their Armor Class when wearing any type of armor.",
    "Berserker's Wrath: In moments of intense anger, the character goes into a berserker rage, attacking the nearest creature, ally or foe.",
    "Sensory Dullness: The character loses one of their senses (sight, hearing, taste, smell, or touch), making daily life and combat more challenging.",
    "Addiction to Shadows: The character becomes addicted to consuming shadowy substances, suffering from withdrawal if they don't indulge.",
    "Beastly Transformation: The character occasionally transforms into a harmless animal, potentially leading to awkward situations.",
    "Summoning Curse: Whenever the character rolls a natural 1 on an attack roll, a chaotic or harmful entity is inadvertently summoned.",
    "Mutagenic Effects: The character experiences random physical mutations, which can have both positive and negative effects on their abilities.",
    "Intrusive Thoughts: The character is plagued by strange and disturbing thoughts, making it difficult to concentrate and imposing disadvantage on Intelligence checks.",
    "Cursed Hunger: The character develops an insatiable appetite for strange or unsavory foods, potentially leading to cannibalistic tendencies.",
    "Growth of Monster Parts: The character's body gradually develops monstrous features, such as horns, claws, or fangs, affecting their appearance and social interactions.",
]