minor_curses_list = [
    "Raven's Caw: You occasionally emit a raven's caw when trying to speak, making stealth difficult.",
    "Misty Vision: Fog and mist seem to follow you, obstructing your vision slightly in certain areas.",
    "Echoing Whispers: You hear faint, unsettling whispers in your mind when in dark or quiet places.",
    "Phantom Chill: You constantly feel a chill running down your spine, making it hard to keep your composure.",
    "Grasping Shadows: Shadows occasionally seem to move on their own, causing unease.",
    "Cobweb Magnet: Cobwebs and spiderwebs cling to you, making you an arachnid's favorite target.",
    "Fading Reflection: Your reflection in mirrors is distorted, appearing as a monstrous version of yourself.",
    "Broken Timepiece: All timepieces you carry run five minutes behind the actual time.",
    "Grave Soil: You always seem to carry the scent of freshly dug graves.",
    "Torn Parchment: Your important documents and maps have a tendency to develop rips and tears.",
    "Restless Sleep: You have vivid nightmares each night, leaving you fatigued in the morning.",
    "Foggy Memory: You occasionally forget important details or have trouble recalling names.",
    "Haunted Whisper: You hear your name whispered from the darkness, even when alone.",
    "Ominous Shadows: Shadows seem to stretch and distort unnaturally in your presence.",
    "Ravenous Crows: Crows follow you, cawing loudly at inopportune times.",
    "Tattered Clothes: Your clothes always seem disheveled and worn, no matter how well-maintained they are.",
    "Cold Grasp: Your touch is always slightly colder than the ambient temperature.",
    "Cobweb Embrace: Spider silk seems to cling to your skin, making it difficult to keep clean.",
    "Shifting Portraits: Portraits and paintings of you seem to change when no one is looking.",
    "Eclipsed Sun: The sun's rays never seem to warm you, and you always feel a chill.",
    "Broken Candles: Candles you light always flicker ominously and go out faster than they should.",
    "Haunted Murmurs: You sometimes hear faint, ghostly murmurs in your ear.",
    "Chilled Bones: Your bones ache with a chill, especially on cold nights.",
    "Unseen Watcher: You feel like you're constantly being watched, even when alone.",
    "Moonlit Stalker: The moon's light always casts eerie, elongated shadows around you.",
    "Whispered Prophecies: You occasionally utter cryptic phrases or prophecies without realizing it.",
    "Wilted Flowers: Flowers in your presence seem to wither and die quickly.",
    "Dampened Spirits: You're prone to bouts of melancholy and sadness.",
    "Vengeful Spirits: You occasionally feel a ghostly presence tugging at your soul.",
    "Gossamer Threads: You always seem to have cobwebs or spider silk on your clothes.",
    "Shifting Gravestones: Gravestones and markers in cemeteries sometimes change their inscriptions when you pass.",
    "Cursed Path: You often encounter misfortune when choosing which path to take.",
    "Echoing Laughter: You occasionally hear distant, eerie laughter.",
    "Phantasmal Footsteps: Ghostly footprints appear behind you as you walk.",
    "Bleak Aura: Your presence seems to darken the mood of those around you.",
    "Corrupted Reflection: You sometimes see a twisted, monstrous version of yourself in reflective surfaces.",
    "Scattered Pages: Books and scrolls you touch tend to lose their pages.",
    "Shrouded Sun: The sun seems to be eternally hidden by clouds when you're outside.",
    "Choking Vines: Vines and plant life grow aggressively in your presence.",
    "Muted Laughter: You occasionally hear faint, mocking laughter in empty rooms.",
    "Fading Starlight: Stars above seem dimmer when you look at them.",
    "Hollow Echo: Your voice occasionally echoes in an eerie, haunting way.",
    "Obscured Portraits: Portraits and images of you become obscured by shadows.",
    "Veiled Moon: The moon always appears hazy and obscured when you see it.",
    "Whispers in the Dark: You hear faint, eerie whispers when in complete darkness.",
    "Phantom Presence: You sometimes feel like an invisible presence is nearby.",
    "Bleeding Ink: The ink on your written words occasionally runs, making them illegible.",
    "Shadowy Hands: Shadows seem to form into ghostly hands in your peripheral vision.",
    "Shifting Tombstones: Tombstones sometimes change positions in graveyards.",
    "Haunting Breeze: A cold breeze seems to follow you, chilling those around you.",
    "Torn Manuscripts: Important texts and parchments you handle develop inexplicable tears.",
    "Broken Reflection: Mirrors and reflective surfaces sometimes show a shattered reflection.",
    "Wailing Spirits: You occasionally hear the distant wails of unseen spirits.",
    "Cursed Quill: Your quill occasionally writes cryptic or disturbing messages on its own.",
    "Lingering Mist: A faint mist often lingers in your presence, even indoors.",
    "Flickering Candlelight: Candles near you always flicker erratically.",
    "Phantom Whispers: You hear indistinct whispers that no one else seems to hear.",
    "Veiled Sun: Sunlight is often dimmed when you're outdoors.",
    "Cryptic Symbols: Strange symbols sometimes appear on surfaces you touch.",
    "Ghastly Odor: An unpleasant odor follows you wherever you go.",
    "Drifting Shadows: Shadows seem to move on their own, even in well-lit areas.",
    "Rattling Chains: You occasionally hear the sound of rattling chains.",
    "Fading Starlight: Stars in the night sky appear to dim when you gaze at them.",
    "Uncanny Echo: Your footsteps occasionally echo unnaturally.",
    "Eerie Breeze: An eerie, chilling breeze often sweeps through your location.",
    "Veiled Moonlight: The moon always appears behind veils of mist.",
    "Tugging Shadows: Shadows seem to reach out and grasp at your feet.",
    "Unsettling Aura: People often feel uneasy or nervous in your presence.",
    "Distant Whispers: You hear distant, unintelligible whispers when you're alone.",
    "Flickering Torches: Torches and flames near you always flicker wildly.",
    "Cursed Inkwell: Your inkwell occasionally spills its contents unexpectedly.",
    "Phantom Touch: You occasionally feel a ghostly touch on your skin.",
    "Dimmed Lanterns: Lanterns and lights near you always seem to grow dim.",
    "Phantom Choir: You hear the eerie voices of an invisible choir in the distance.",
    "Unsettling Reflection: Your reflection occasionally appears distorted in mirrors.",
    "Shadowy Figures: You occasionally see shadowy figures in your peripheral vision.",
    "Eclipsed Stars: Stars above you always seem obscured by clouds.",
    "Phantom Footprints: Ghostly footprints often appear before you.",
    "Hidden Faces: People's faces sometimes appear obscured when you look at them.",
    "Darkened Aura: A shadowy aura often surrounds you, dimming the area.",
    "Tainted Waters: Water in your presence sometimes turns murky and foul.",
    "Veiled Suns: Sunlight is always obscured by passing clouds when you're outdoors.",
    "Twisted Visions: You sometimes see unsettling and twisted images in mirrors.",
    "Echoing Whispers: You hear faint, haunting whispers when in complete silence.",
    "Fading Moonlight: The moon always appears dimmer when you gaze at it.",
    "Phantom Shadows: Shadows sometimes seem to move independently.",
    "Ominous Breeze: An ominous breeze often rustles nearby foliage.",
    "Veiled Faces: You occasionally see faces in the fog or mist that aren't really there.",
    "Muffled Sounds: Sounds in your vicinity sometimes become muffled and indistinct.",
    "Flickering Flames: Flames near you always seem to flicker strangely.",
    "Phantom Tug: You sometimes feel as if someone is tugging at your clothing.",
    "Tainted Aura: Your presence sometimes causes people to feel uneasy.",
    "Hidden Words: Words on pages you read occasionally seem to vanish.",
    "Distant Footsteps: You hear faint footsteps when no one is around.",
    "Drifting Fog: A faint fog often follows you when you're outdoors.",
    "Flickering Shadows: Shadows seem to flicker and jump around you.",
    "Uncanny Silence: You occasionally hear eerie, unnatural silence.",
    "Whispers on the Wind: You hear distant whispers carried by the wind.",
    "Muted Colors: Colors in your presence sometimes appear muted and dull.",
    "Chilling Gaze: People sometimes feel a sudden chill when you look at them."
]