wild_magic_pact_list = [
    "You Explode: A 3rd Level Fireball Spell Centred on you detonates using your Constitution as the Spell Casting Ability. You are set on fire as a result of this explosion and take 1d6 Fire Damage at the start of each of your turns until your Rage ends.",
    "For the duration of your Rage, when a Creature within 60ft you takes Damage except from this Ability, all Creatures within 60ft take the same amount of Damage.",
    "A 30 ft. cube of Ice materialises centred on you, Creatures within are Restrained, have no air and take 1d6 Cold damage at the start of their Turn until they escape the Cube. The Cube has an AC of 5 and Hit Points equal to five times your Constitution Ability Modifier.",
    "A black hole opens in your chest for the duration of your Rage, all Creatures within 60ft. must make a Strength Saving Throw or be pulled towards you 30ft at the start of their Turns. You must make a Dexterity Saving Throw or take 1d10 bludgeoning Damage at the start of your Turn as you are pelted by debris.",
    "Hundreds or arms grow out of your back and Grapple all creatures within 15 ft. using your Athletics Skill for the duration of your Rage.",
    "Your body begins emanating inky magical darkness for the duration of your Rage, all Creatures within 10 ft of you are Blinded.",
    "Animated chains rise out of the floor, all Creatures within 30ft. centred on you must make a Strength Saving Throw or be Restrained by the chains until your Rage ends. A Creature restrained by the chains can use its action to repeat the Strength Saving Throw; on a success, it frees itself.",
    "For the duration of your Rage the floor within 60 ft Radius of you turns to knee deep custard, any Creature that did not move at least 10 ft. on its Turn is restrained and must make a Strength Saving Throw to free itself on a success.",
    "Your maximum hit points is how many Hit Points of creatures this ability can affect. Creatures starting with you and then within 20ft are affected in ascending order of their current Hit Points (ignoring Creatures with the Unconscious Condition). Starting with the Creature that has the lowest Current Hit Points, each Creature affected by this Ability falls Unconscious for 1 Hour, until the sleeper takes Damage, or someone uses an Action to shake or slap the sleeper awake. Subtract each creature's Hit Points from the total before Moving on to the Creature with the next lowest Hit Points. A Creature's Current Hit Points must be equal to or less than the remaining total for that Creature to be affected",
    "Ball bearings spill out of your clothing within a 60ft Radius, each Creature standing in its area must succeed on a Dexterity saving throw at the start of their Turn or fall Prone.",
    "You are reduced to a child for the duration of your Rage; your Speed, Damage, and Armor class are halved, and all Checks are made at Disadvantage.",
    "Your bones vanish for the duration of your Rage, you are Immune to Bludgeoning damage but automatically fail all Strength Ability Checks. Your Speed is halved.",
    "You become grotesquely fat for the duration of your Rage; you are Immune to piercing Damage but automatically fail all Dexterity Ability Checks. Your Speed is halved.",
    "You turn into translucent jelly for the duration of your Rage, you are Immune to Slashing Damage but automatically fail any Constitution Ability Checks. Your Speed is halved.",
    "Your legs are replaced by a slug's foot for the duration of your Rage, your Speed is reduced to 10 ft and you gain the effects of the Spider Climb Spell.",
    "Your arms are replaced by fins for the duration of your Rage, you can not hold a Weapon and gain a Swim Speed equal to double your Walking Speed.",
    "You sprout one giant wing from your back for the duration of your Rage, as a Bonus Action you can make a Wing Buffet Attack using your Strength and Proficiency Bonus, that deals 1d6 + your Strength Ability Modifier Bludgeoning Damage and Forces your Target back 5ft, but you must make a Strength Saving Throw of DC (10+ the Damage Result) or gain the Prone Condition due to the force of the flap.",
    "You grow gills for the duration of your Rage, you lose the ability to breath air and gain Water Breathing, you can also spit a 15 ft cone of viscous goo as a Bonus Action, Creatures caught in the cone must make a Dexterity Saving Throw or take 4d4 Acid Damage.",
    "Your eyes are replaced with compound eyes for the duration of your Rage, you can not be Flanked but you have Disadvantage on all Perception Checks that rely on sight.",
    "You grow a second head for the duration of your Rage gaining Advantage on Intelligence and Wisdom Saving Throws as well as Perception Checks, but Creatures Attacking you have their Critical Hit Range doubled.",
    "For the duration of your Rage, all Creatures that start their Turn within 60ft of you randomly switch places with another Creature within the same Radius.",
    "While you are Raging, the ground around you for 20ft becomes semi-fluid like a waterbed while the air bends and shifts, it is considered Difficult Terrain.",
    "While you are Raging, at the start of your Turn roll a 1d6 to determine direction and a 1d6x5 to determine distance, at that location a 5ft pool of Lava opens up and remains until 1d6 rounds after your Rage ends.",
    "When you Rage, 5ft square pieces of Green Slime are created equal to your Constitution Ability Modifier and are equally spaced about in a 60ft Radius in unoccupied spaces. They last 1d6 rounds after your Rage ends.",
    "When you Rage a 30ft Radius snowstorm centred on you whips up, each Creature apart from you in that area must make a DC 10 Constitution Saving Throw or take 1 point of Exhaustion. Perception Checks and Attacks have Disadvantages in the area. The storm persists one turn after your Rage ends.",
    "A 60 ft cube of water is summoned centred on you that does not spill and exists for (1 + Constitution Ability Modifier) minutes.",
    "When you Rage gravity within 120ft of you is turned 90 degrees in a random direction until your Rage ends.",
    "When you Rage all the effects of the Silence Spell are applied in a 20ft Radius centred on you for the duration of your Rage.",
    "When you Rage, all Creatures within 60ft’s legs are replaced with the bottom of random Chess pieces and can only move like those pieces. This effect ends when your rage ends. \n\n* King: 5ft any direction \n* Queen: 40ft in a straight line, in any direction. \n* Rook: 40ft in a straight line, in a cardinal direction. \n* Bishop: 40ft in a straight line diagonally. \n* Knight: 10 ft in a straight line, in a cardinal direction, then 5ft to the left or right. \n* Pawn: 5ft North or South, once you move in one direction you can't move in the other.",
    "A dimensional tear to the Astral Sea opens within 30 ft Radius of you for the duration of your Rage, Creatures that enter the zone lose all movement and gain a Fly(Hover) Speed of ten times their Intelligence Ability Modifier (minimum 10 ft).",
    "While your Raging Creatures you cut bleed Money equal to the Damage you Deal in Silver Pieces.",
    "While Raging, as a Bonus Action you can make a Gaze Ranged Attack using your Constitution Ability Modifier and Proficiency Bonus, if you Hit you can alter the cut, style and colour of the clothes of the Target.",
    "While you are Raging, the light within 20ft takes on a deep red hue and a choir starts singing, you have Advantage on Intimidation Checks.",
    "While you are Raging you can summon custard pies out of thin air and make a Ranged Weapon Attack, if you Hit the Creature has Disadvantage on Charisma Checks for 1d4 minutes.",
    "When you Rage Creatures are randomly attached together in a pair until no more pairs can be made, they are attached by rubber bands that pull them 5ft closer to each other each at the start of their Turns and will not allow them to be more than 20ft. apart until the Rage ends.",
    "For the duration of your Rage, each Action you take is accompanied by musical cue’s and cartoon sound effects that can be heard up to 60ft. away.",
    "Your Weapon becomes Sentient for the duration of your Rage, it has an Intelligence, Wisdom and Charisma score are equal to your own and can speak out loud as well as has Hearing and normal Vision to 30 ft.",
    "For the duration of your Rage any mundane object your mime to have about your person functions as if it exists.",
    "While you are Raging, you may cast the Cutting Words Cantrip.",
    "While you are Raging, as an Action you can summon a cow to drop from the sky, the Target needs to make a Dexterity Saving Throw or take 2d10 Bludgeoning Damage and gain the Prone Condition.",
    "Your legs turn into springs for the duration of your Rage, and you can Jump in any direction up to your full movement.",
    "Your arms become long noodles for the duration of your rage and your Reach increases 10ft.",
    "Your head swells up like a balloon for the duration of your Rage and you gain a Flying(Hover) Speed of half your Walking Speed and are Immune to the Prone Condition.",
    "Your hair grows and becomes prehensile for the duration of your Rage, you can use it to make Grapple Check as a Bonus Action with a range of 10ft.",
    "Your body grows quills for the duration of your Rage. You can use it to make a Ranged Weapon Attack, Range 30/60ft, that deals 1d6 + your Dexterity Ability Modifier Piercing Damage and on a Hit the Target needs to make a Constitution Saving Throw or gain the Poisoned Condition.",
    "Your insides become mechanical for the duration of your Rage; you become Immune to the Charmed, Exhaustion, Frightened, Paralyzed, Petrified and Poisoned Conditions but cannot be Healed, only mended.",
    "While Raging your torso can spin like a propeller allowing you to make a Single Weapon Attack against all Targets within 5ft as an Action. On a Hit they are Forced back 5ft.",
    "Your nose enlarges and your mucus becomes sticky and elasticated while you Rage, as a Bonus Action you can sneeze a web of gunge at a target with a Ranged Weapon Attack, range 40/120 ft. If it Hits the Target gains the Restrained Condition. As an Action, the Creature can make a Strength Saving Throw, bursting the gunge and ending the Condition on a success. The gunge can also be attacked and destroyed (AC 12; hp 10, Immunity to bludgeoning, poison, and psychic damage) ending the Condition.",
    "Your body melts and becomes bright pink gunge, you are considered amorphous, able to move through spaces 1 inch wide without squeezing. You are Immune to the Grappled and Prone Conditions.",
    "While you are Raging, your body grows battlements and arrow slits as well as an army of tiny soldiers. On initiative count 20 the soldiers inside fire two tiny catapults at your enemies (Your Modifier for a Ranged Weapon Attack/40ft/1d6+ your Proficiency Bonus Bludgeoning Damage) and shoot a volley of arrows (10ft cone, Xd4 where X is your Proficiency Bonus Piercing Damage, Dexterity Saving Throw for half).",
    "As a Bonus Action while Raging, you can magically create an armed Hunting Trap at any location you can see.",
    "While you are Raging you can create an infinite amount of Silk Rope by pulling it out of your sleeve, pocket or pouch.",
    "As long as you are Raging, you can create energy axes as a Free Action that lasts one Round and function as a Hand Axe +1 that deals Radiant Damage instead of Slashing.",
    "At the start of each Turn, while you are Raging, you can create a ball from the Grey Bag of Tricks.",
    "When you Rage; your mouth opens and you vomit a stream of 1d4 x 10 gems, each worth 1 gp, in a line 30 feet long and 5 feet wide. Each gem deals 1 Bludgeoning Damage, and the total damage of the gems is divided equally among all creatures in the line.",
    "As a Bonus Action while you are raging you can shoot a Swarm of Insects out of your eyes into an adjacent 5ft square. You do not control the created Swarms.",
    "Your weapon gains the Dancing Quality for the duration of your Rage; it gains a Flying (Hover) Speed of 30ft and Attacks one creature of your choice within 5ft of it. \n\nThe sword uses your Attack Modifier and Ability Modifier to Damage Rolls. While it hovers, you can use a Bonus Action to cause it to Fly up to 30ft to another spot within 30ft of you. As part of the same Bonus Action, you can cause the sword to Attack one Creature within 5ft of it. \n\n After it Attacks for the fourth time, it flies up to 30ft and tries to return to your hand. If you have no hand free, it falls to the ground at your feet. If it has no unobstructed path to you, it moves as close to you as it can and then falls to the ground. It also ceases to hover if you grasp it or move more than 30ft away from it.",
    "While your Rage persists, at the start of each Turn a Melf's Minute Meteor as per the Spell is summoned into being around you under your control.",
    "When you Rage a Tiny Fey being is summoned into existence on your shoulder that shouts encouragement and grants you a d6 Bardic Inspiration Die if you don’t have one. The being exists for 1d8 turns.",
    "When you Rage a Friendly Unicorn materialises to aid you for 1D8 Turns.",
    "Your body emits a thick cloud of bubbles in a 10ft Radius. People other than you caught in the cloud have Disadvantage on Attacks and Resistance to Fire Damage.",
    "While you Rage you emit a 30ft Radius cloud of fog that Heavily Obscures everything within it.",
    "While Raging you emit a flaming Aura, whenever someone starts their turn within 10ft of you, they take 1d6 Fire Damage. You also have Resistance to Cold Damage.",
    "A shower of glitter rains down around you in a 10ft radius while you Rage, all Creatures entering the Radius must make a Dexterity Saving Throw or are outlined by the glitter, negating the Invisible Condition and Attacks against them have Advantage for 1d4 Turns.",
    "The sound of soothing music emits from your body while you Rage, the Frightened Condition is suppressed on creatures within 10ft of you.",
    "Until your Rage ends, soft feathers drift around you in a 10ft Radius, everyone inside the Radius has Resistance to Bludgeoning, Slashing and Piercing Damage.",
    "For the duration of your Rage, a cloud of luminous fairies swarms around within 20ft., all Creatures that start their Turn within the Radius Heal 1d8 Hit points.",
    "You emit an aura of sparkling pink hearts, Creatures that start their Turn within 10ft of you must make a Charisma Saving Throw or be Charmed by you.",
    "While you Rage the air around you crackles with lightning and you have Resistance to Lightning Damage, as a Reaction you can make a Ranged Spell Attack at a Creature within 20ft, on a hit you deal 1d6 + your Proficiency Bonus Lightning Damage, if it is wearing metal it takes an additional 1d6 Lighting Damage.",
    "Blades begin spinning in a 10ft Radius around you as part of your Rage, Creatures that start their Turn there take 2d6 + your Proficiency Bonus Slashing Damage. As a Reaction you can parry a strike adding +2 to your AC.",
    "You regain all your uses of Bolstering Magic.",
    "You have the Magic Resistance Trait while you Rage.",
    "Whenever a Creature Hits you with an Attack before your Rage ends, that Creature takes 1d6 Force Damage, as magic lashes out in retribution.",
    "Any Creature you reduce to 0 Hit Points while Raging gains the Petrified Condition instead of the Dyning Condition.",
    "While Raging If a Creature is reduced to 0 Hit Points Dies, its corpse turns into a gold statue worth Its CR X 100 Gold. This does not interfere with Magic that returns Creatures to life.",
    "While you are Raging if you Hit with a Melee Weapon, you can cast Dispel Magic on the Target as a Bonus Action.",
    "When you Rage you cast the Spell Armor of Agathys on yourself as a Warlock of the same level.",
    "When you Rage you cast the Spell Deathward on yourself.",
    "While you Rage As a Bonus Action you can gain the Invisible Condition until the start of your next Turn or until you take an Action, Bonus Action or Reaction.",
    "You can step on air as if it is a solid surface while you Rage.",
    "Instead of Raging you Wild Shape as a Circle of the Moon Druid of the same Level.",
    "You grow spines like a porcupine, any Creature Grappled or Grappling you takes 1d6 Piercing Damage.",
    "You grow a Star-nosed mole’s nose and gain Tremor Sense 120ft until your Rage ends.",
    "You grow four giant spider legs and are under the effects of the Spider Climb Spell, you also have Advantage on Athletics Checks and Saving Throws against the Prone Condition until your Rage ends.",
    "While you're Raging, if you have Grappled someone, you can make a second Grapple Check and if you succeed you swallow them. You can swallow one medium or smaller Creature, While they are swallowed there have the Restrained Condition and take 1d8 Acid and 1d8 Bludgeoning Damage at the start of their Turn, if your Rage ends or they deal more than 20 damage to you in a Turn, you vomit them back out.",
    "Your hands become Crab Claws that can make Melee Weapon Attacks that deal 2d8 + your Strength Ability Modifier, the Target is automatically Grappled on a Hit.",
    "While Raging, you grow four tentacles round your mouth, As a Bonus Action you can make Melee Attacks equal to your Proficiency Bonus with these tentacles and they deal 1d6 + your Intelligence Ability Modifier Psychic Damage.",
    "Your skeleton becomes adamantium and you become Immune to Critical Hits until your Rage ends.",
    "You split into two bodies for the duration of your Rage, both count as the same Creature except it has two bodies, can grant itself Flanking and give assistance to itself with Skill Checks.",
    "You grow two additional arms for the duration of your Rage that can wield a weapon between them and if you make an Off-Hand Attack as a Bonus Action you can make two Attacks instead of one.",
    "For the duration of your Rage your head transforms into a Red Dragons head, you can make a 20ft Cone Breath Weapon (Recharge on a 6) Attack as an Action, that deals Xd6 where X is your Proficiency Bonus Fire Damage. Half as much on a successful Dexterity Saving Throw.",
    "You grow Feathered wings for as long as you’re raging,  you gain a 30ft Fly Speed, as a Reaction you can close them around you and halve the Damage from a single Attack or Spell.",
    "You grow Bat wings for as long as you’re Raging, you gain a 30ft Fly Speed, as a Reaction if you are Hit you can move up to 30ft without provoking an Attack Of Opportunity.",
    "While you’re Raging you gain 1/day Counterspell.",
    "When you Rage, you fire a 3rd level Lightning Bolt as per the Spell out of your eyes.",
    "One of your Weapons becomes an energy weapon that makes a loud humming noise and deals an additional 2d6 Radiant Damage until your Rage ends.",
    "As long as your Rage lasts you can Teleport 60ft to space you can see as a Bonus Action.",
    "Creatures up to your Constitution Ability Modifier of your choice gain Truesight for the duration of your Rage.",
    "When you Rage you cast Magic Missiles at the highest level possible for a Wizard of the same level",
    "You are surrounded by a burning golden aura while you Rage. Your Strength, Constitution and Dexterity Ability Modifier, as well as your Speed, is doubled for the duration of your Rage. You Heal 1d12+ your Constitution Ability Modifier in Hit Points at the start of your Turn.",
]