catastrophes_list = [
    "Flood",
    "Flood",
    "Sandstorm",
    "Sandstorm",
    "Curse",
    "Curse",
    "Tornado",
    "Tornado",
    "Packs of Wolves",
    "Packs of Wolves",
    "Earthquake",
    "Earthquake",
    "Roving Giants",
    "Roving Giants",
    "Locusts",
    "Locusts",
    "Hurricane",
    "Hurricane",
    "Disease",
    "Disease",
    "Mudslide",
    "Mudslide",
    "Scorpions",
    "Scorpions",
    "Stampede",
    "Stampede",
    "Raiding Bands",
    "Raiding Bands",
    "Frogs",
    "Frogs",
    "Thunderstorm",
    "Thunderstorm",
    "Fire",
    "Fire",
    "Hauntings",
    "Hauntings",
    "Windstorm",
    "Windstorm",
    "Blizzard",
    "Blizzard",
    "Siege",
    "Siege",
    "Meteorite",
    "Meteorite",
    "War",
    "War",
    "Disappearances",
    "Disappearances",
    "Tsunami",
    "Tsunami",
    "Monsoon",
    "Monsoon",
    "Rats",
    "Rats",
    "Poisoned Water",
    "Poisoned Water",
    "Pestilence",
    "Pestilence",
    "Troll Raiders",
    "Troll Raiders",
    "Drought",
    "Drought",
    "Band of Thieves",
    "Band of Thieves",
    "Snakes",
    "Snakes",
    "Genocide",
    "Genocide",
    "Serial Killer",
    "Serial Killer",
    "Hailstorm",
    "Hailstorm",
    "Blight",
    "Blight",
    "Pirates",
    "Pirates",
    "Volcanic Eruption",
    "Volcanic Eruption",
    "Famine",
    "Famine",
    "False Prophet",
    "False Prophet",
    "Rabid Bears",
    "Rabid Bears",
    "Conquered",
    "Conquered",
    "Trickster Fairy",
    "Trickster Fairy",
    "Madness",
    "Madness",
    "Occupation",
    "Occupation",
    "Darkness",
    "Darkness",
    "Bands of Cannibals",
    "Bands of Cannibals",
    "Undead Horde",
    "Undead Horde",
    "Dragon",
    "Dragon"
]