culinary_herbs_and_spices_list = [
    'Allspice',
    'Angelica',
    'Barberry',
    'Basil, sweet',
    'Basil, holy',
    'Bay leaf',
    'Borage',
    'Blue Fenugreek',
    'Caper',
    'Caraway',
    'Cardamom',
    'Cardamom, black',
    'Cassia',
    'Catnip',
    'Celery Leaf',
    'Celery Seed',
    'Chicory',
    'Chili Pepper',
    'Chives',
    'Cicely',
    'Cilantro, coriander herb',
    'Cinnamon, true',
    'Cinnamon, white',
    'Clary',
    'Clove',
    'Coriander Seed',
    'Costmary',
    'Cubeb Pepper',
    'Culantro',
    'Cumin',
    'Curry Leaf',
    'Curry Plant',
    'Dill Herb or Weed',
    'Dill Seed',
    'Elderflower',
    'Fennel',
    'Fenugreek',
    'Filé powder',
    'Fingerroot',
    'Galingale',
    'Garlic Chives',
    'Ginger',
    'Grains of Paradise',
    'Grains of Selim',
    'Horseradish',
    'Hyssop',
    'Jasmine Flowers',
    'Juniper Berry',
    'Lavender',
    'Lemon Balm',
    'Licorice',
    'Lime Flower',
    'Lovage',
    'Mace',
    'Marjoram',
    'Mint',
    'Musk Mallow',
    'Mustard, black',
    'Mustard, brown',
    'Mustard, yellow',
    'Nutmeg',
    'Oregano',
    'Orris Root',
    'Paprika',
    'Parsley',
    'Pepper, black, white, and green',
    'Pepper, mountain',
    'Peppermint',
    'Rosemary',
    'Rue',
    'Safflower',
    'Saffron',
    'Sage',
    'Salad Burnet',
    'Sassafras',
    'Savory, summer',
    'Savory, winter',
    'Silphium',
    'Sorrel',
    'Sorrel, sheep',
    'Spearmint',
    'Spikenard',
    'Star Anise',
    'Sumac',
    'Sweet Woodruff',
    'Tarragon',
    'Thyme',
    'Turmeric',
    'Vanilla',
    'Water-pepper',
    'Watercress',
    'Wattleseed',
    'Wild Thyme',
    'Willow Herb',
    'Wintergreen',
    'Wood Avens',
    'Woodruff',
    'Wormwood, absinthe',
    'Yarrow',
    'Zedoary'
]
