medicinal_herbs_list = [
    'Abscess Root',
    'Açai',
    'Alfalfa',
    'Aloe Vera',
    'Arnica',
    'Asafoetida',
    'Ashoka Tree',
    'Asthma-plant',
    'Astragalus',
    'Barberry',
    'Belladonna',
    'Bilberry',
    'Bitter Gourd',
    'Bitter Leaf',
    'Bitter Orange',
    'Black Cohosh',
    'Blessed Thistle',
    'Burdock',
    'Cat’s Claw',
    'Cayenne',
    'Celery',
    'Anthemis Nobilis',
    'Chaparral',
    'Chasteberry',
    'Cinchona',
    'Comfrey',
    'Digitalis (Foxglove)',
    'Dong Quai',
    'Elderberry',
    'Ephedra',
    'Eucalyptus',
    'European Mistletoe',
    'Evening Primrose Oil',
    'Fenugreek',
    'Feverfew',
    'Flaxseed',
    'Garlic',
    'Ginger',
    'Ginkgo',
    'Ginseng',
    'Goldenseal',
    'Guava',
    'Gum Arabic',
    'Hawthorn',
    'Henna',
    'Hibiscus',
    'Hoodia',
    'Horse Chestnut',
    'Horsetail',
    'Jamaica Dogwood',
    'Kava',
    'Khat',
    'Konjac',
    'Kratom',
    'Kanna',
    'Lavender',
    'Licorice Root',
    'Lotus',
    'Marigold',
    'Marsh-mallow',
    'Moringa Oleifera',
    'Milk Thistle',
    'Neem',
    'Noni',
    'Opium Poppy',
    'Oregano',
    'Papaya',
    'Peppermint Oil',
    'Purple Coneflower',
    'Passion Flower',
    'Red Clover',
    'Rosemary',
    'Sage',
    'Syrian Rue (Harmal)',
    'St. John’s Wort',
    'Saw palmetto',
    'Summer Savory',
    'Tea Tree Oil',
    'Thunder God Vine',
    'Thyme',
    'Tulsi (Holy Basil)',
    'Turmeric',
    'Umckaloabo',
    'Valerian',
    'Velvetleaf',
    'Verbena',
    'Veronica',
    'Vetiver',
    'Wafer Ash (Hoptree)',
    'Wahoo',
    'Wallflower',
    'Water Dropwort',
    'Water Germander',
    'Water Hemlock',
    'Water Plantain',
    'Watercress',
    'Wheatgrass',
    'White Willow',
    'Xanthoparmelia Scabrosa',
    'Yerba Santa'
]