adventurers_dead_body_items = [
    "Backpack (empty)",
    "Rope (50’)",
    "Copper pieces (1D4)",
    "Club",
    "Map to a dungeon",
    "Silver pieces (1D4)",
    "Last will and testament",
    "Rations (1D6 days)",
    "Platinum pieces (1D4)",
    "Gold tooth",
    "Gold pieces (1D20)",
    "Rations (moldy)",
    "Long sword",
    "Studded leather",
    "Electrum pieces (1D4)",
    "Long bow",
    "Dagger",
    "Ancient text describing a mythical city",
    "Leather armor",
    "Ruby (50 gp)",
    "Map of a dungeon",
    "Arrow",
    "Copper pieces (1D6)",
    "Prayer book",
    "Poison (1 vial)",
    "Journal",
    "Platinum pieces (1D6)",
    "Key engraved with a strange symbol",
    "Leather belt",
    "Silver pieces (1D12)",
    "Bestiary",
    "Copper (1D8)",
    "Letters",
    "Ring (25% chance magical)",
    "Short bow",
    "Electrum pieces (1D6)",
    "Spell book",
    "Short sword",
    "Gold pieces (1D8)",
    "Beef jerky (1D4 sticks)",
    "Copper pieces (1D10)",
    "Chewing tobacco",
    "Rations (1D4 days)",
    "Bearskin cloak",
    "Electrum pieces (1D8)",
    "Spear",
    "Platinum pieces (1D8)",
    "Crossbow blots (1D6)",
    "Amulet (25% change magical)",
    "Copper pieces (1D12)",
    "Gold pieces (1D6)",
    "Dragon’s tooth",
    "Water skin (full)",
    "Shackles",
    "Whisky (half full)",
    "Odd scroll (25% change magical)",
    "Spare bowstring",
    "Silver ring",
    "Arrows (1D8)",
    "Electrum pieces (1D10)",
    "Staff",
    "Crossbow",
    "Rations (1D8 days)",
    "Locket with drawing of a person",
    "Platinum pieces (1D10)",
    "Iron ring",
    "Boots",
    "Silver pieces (1D20)",
    "Contract",
    "Great sword",
    "Dice set",
    "Emerald (100 gp)",
    "Electrum pieces (1D12)",
    "Bounty notice",
    "Chain shirt",
    "Gold pieces (1D8)",
    "Handkerchief",
    "Broken bow",
    "Iron armor",
    "Platinum pieces (1D12)",
    "Copper pieces (1D20)",
    "Heavy Cloak",
    "Gold ring",
    "Silver pieces (1D10)",
    "Hymnbook",
    "Battleaxe",
    "Arrows (1D12)",
    "Electrum pieces (1D20)",
    "Small wooden puzzle box",
    "Keys (1D8)",
    "Platinum pieces (1D20)",
    "Melted sword",
    "Copper pieces (1D100)",
    "Locket with a lock of hair",
    "Crossbow bolts (1D10)",
    "Silver pieces (1D100)",
    "Letter from someone begging for help",
    "Electrum pieces (1D100)",
    "Deed to a castle in a faraway land",
    "Gold pieces (1D100)"
]