bandit_hideout_items = [
    "Gold pieces (1D4)",
    "Slaves (1d4)",
    "Short sword",
    "Bag of human teeth",
    "Cheese wheel",
    "Dagger",
    "Iron helmet",
    "Long sword",
    "Cloak (worn)",
    "Arrows (1D10)",
    "Great sword",
    "Bear pelt",
    "Keg of ale",
    "Stuffed bear",
    "Morningstar",
    "Studded leather armor",
    "Caged wolf",
    "Kidnapped child",
    "Smooth stone",
    "Pike",
    "Golden circlet",
    "Blueprints of the local outpost",
    "Normal clothing",
    "Rusted armor",
    "Spear",
    "Caged rats",
    "Broken helmet",
    "Gold pieces (1d20)",
    "Slaves (1D8)",
    "Vial of poison",
    "Ruby",
    "Helmet with deer antlers",
    "Elf skull",
    "Arrow (1D6)",
    "Wolf pelt",
    "Cooper pieces (1D100)",
    "Peg leg",
    "Silver pieces (1D6)",
    "Bandages",
    "Caged squirrel",
    "Basket of apples",
    "Deer pelts (1D6)",
    "Leather armor",
    "Dragon claw",
    "Silver pieces (1D20)",
    "Town guard patrol routes",
    "Chest of bones",
    "Gloves",
    "Pearl",
    "Incriminating letter",
    "Wolf pelts (1D8)",
    "Drums",
    "Deer alters",
    "Keg of mead",
    "Beef jerky (1D8 sticks)",
    "Noble’s ring",
    "Foreign sword",
    "Iron armor",
    "Emerald",
    "Falsified city papers",
    "Cloak (new)",
    "Jade",
    "Wizard’s staff",
    "Venison steaks (1D4)",
    "Boots",
    "Tinderbox",
    "Caged bear",
    "Cloak (new)",
    "Arrows (1D4)",
    "Journal",
    "Lute",
    "Silver pieces (1D100)",
    "Torture tools",
    "Cooper pieces (1D20)",
    "Locked chest",
    "Bear skull",
    "Wand",
    "Wolf pelts (1D10)",
    "Mace",
    "Fishing gear",
    "Wooden sword",
    "War axe",
    "Deer pelts (1D10)",
    "Sapphire",
    "Caged snake (venomous)",
    "Treasure map",
    "Arrows (1D20)",
    "Prisoner",
    "Loaf of moldy bread",
    "Battleax",
    "Unsent letter",
    "Scimitar",
    "Bear skin cloak",
    "Gold pieces (1D100)",
    "Bear pelts (1D4)",
    "Slaves (1D10)",
    "Bag of gems",
    "Dragon egg",
    "Diamond",
    "Spell book"
]