cottage_items = [
    "Rodent droppings",
    "Mushrooms (1D6)",
    "Deer pelt",
    "Broken longbow",
    "Boiling soup",
    "Freshly picked flowers",
    "Carrots (1D8)",
    "Dried herbs",
    "Basket of rotten vegetables",
    "Fresh corpse",
    "Single rose",
    "Fine cloak",
    "Beer mug",
    "Dying fire",
    "Lone hunter",
    "Melons 1D6",
    "A magic mirror",
    "Completely empty",
    "Freshly baked apple pie",
    "Mounted goblin head",
    "Stuffed bear",
    "Bloodstains",
    "Partially sewn dress",
    "Recipe for hangover elixir",
    "Hermit (unintelligible)",
    "Intoxicating smell",
    "Child’s skull",
    "Unsent love letter",
    "Unfinished meal",
    "Fishing gear",
    "Hunters (1D4)",
    "Broken rocking chair",
    "Hatch in the floor",
    "Crystal ball",
    "Empty cauldron",
    "Adventurer’s journal",
    "Broken table",
    "Fresh loaf of bread",
    "Apples (1D8)",
    "Bucket of lard",
    "Lynched man",
    "Hot cider",
    "Kegs of ale (1D4)",
    "Dead rodents (1D4)",
    "Lute",
    "Fresh raspberries",
    "Romantic dinner for two",
    "Torn up letter",
    "Carrots (1D12)",
    "Spiders",
    "Lukewarm tea",
    "Bundle of firewood",
    "Rotten apples (1D12)",
    "Book about plants",
    "Mounted deer head",
    "Animal cage",
    "Fresh blueberries",
    "Moldy raspberries",
    "Incense",
    "Clothesline",
    "Dried chicken feet",
    "Jar of eyes",
    "Freshly brewed green tea",
    "Blood soaked journal",
    "Gran’s recipe book",
    "Spindle",
    "Bundles of cloth (1D6)",
    "Wolf pelt",
    "Tattered old cloak",
    "Key ring (1D12 keys)",
    "Locked cupboard",
    "Rusted chest",
    "Injured hunter",
    "Water bucket",
    "Lye soap",
    "Moldy walls",
    "Foreign spices",
    "Maps of local area",
    "Fresh herbs",
    "Moldy blueberries",
    "Tomatoes (1D8)",
    "Potatoes (1D6)",
    "Turnips (1D12)",
    "Basket of wilted flowers",
    "Torn up floor boards",
    "Shrine to a god",
    "Baked beans",
    "Needle and thread",
    "Hooded cloak caked in mud",
    "Old bear trap",
    "Smoking pipe",
    "Longbottom leaf (1D8)",
    "Old rocking chair",
    "Broken bed",
    "Bear skin rug",
    "Butter churn",
    "Goat’s milk",
    "Whistling tea kettle",
    "Broken window pane",
    "Family quilt"
]