fantasy_desk_items = [
    "Vellum (1 sheet)",
    "Wanted Posters (1D4)",
    "Candles (1D6)",
    "Ink Bottles (1D4 empty)",
    "Dagger with Deer Antler Handle",
    "Vellum (1D4 sheets)",
    "Gold Pieces (1D6)",
    "Gold Pieces (1D10)",
    "Book of Local History",
    "Spell Scroll (level 1)",
    "Ink Blotter",
    "Copper Pieces (1D10)",
    "Contract",
    "Foreign Coin (Silver)",
    "Wax (1D6 cubes)",
    "Map of Nearby City",
    "Silver Arrowhead",
    "Quill",
    "Keys (1D6)",
    "Ivory Statuette",
    "Parchment (1D8 sheets)",
    "Wanted Poster",
    "Metal Bowl",
    "Parchment (1D20 sheets)",
    "Quills (1D6)",
    "Spell Scroll (level 3)",
    "Silver Pieces (1D10)",
    "Wax (2 cubes)",
    "Map of the Town",
    "Account Ledger",
    "Copper Pieces (1D20)",
    "Signet Ring",
    "Ribbon (2’)",
    "Silver Pieces (1D6)",
    "Spell Scroll (level 2)",
    "Candles (2)",
    "Copper Pieces (1D8)",
    "Parchment (1 sheet)",
    "Ink Bottles (1D6 full)",
    "Parchment (2 sheets)",
    "Gold Pieces (1D20)",
    "Wanted Posters (1D6)",
    "Wooden Bowl",
    "Vellum (1D8 sheets)",
    "Small Piece of Amber with a Fly Inside",
    "Incriminating Letter",
    "Abacus",
    "Daggers (2)",
    "Parchment (1D10 sheets)",
    "Ink Bottle (full)",
    "Silver Pieces (1D8)",
    "Ink Bottles (1D4 full)",
    "Paper Weight",
    "Ink Bottles (1D6 empty)",
    "Bust of Legendary Leader",
    "Parchment (1D12 sheets)",
    "Copper Pieces (1D6)",
    "Flint and Tinder",
    "Quills (1D4)",
    "Map to a Hidden Mine",
    "Book of Poems",
    "Compass",
    "Silver Pieces (1D12)",
    "Metal Cup",
    "Silver Pieces (1D4)",
    "Copper Pieces (1D4)",
    "Rabbit’s Foot",
    "Prayer Book",
    "Keys (1D4)",
    "Vellum (1D12 sheets)",
    "Half a Map to a Treasure Hoard",
    "Parchment (1D4 sheets)",
    "Map of Shipping Routes",
    "Map to a Dungeon",
    "Keys (1D8)",
    "Dagger",
    "Love Letter",
    "Wax (3 cubes)",
    "Map of Trade Routes",
    "Wooden Cup",
    "Gold Pieces (1D12)",
    "Copper Pieces (1D12)",
    "Parchment (1D6 sheets)",
    "Mummified Monkey Hand",
    "Wax (1 cube)",
    "Vellum (1D8 sheets)",
    "Vellum (1D20 sheets)",
    "Hit List",
    "Map of the Stars",
    "Candle",
    "Vellum (1D10 sheets)",
    "Foreign Coin (Gold)",
    "Scarab Broach",
    "Gold Pieces (1D8)",
    "Key",
    "Silver Pieces (1D20)",
    "Ceramic Vase",
    "Gold Pieces (1D4)",
    "Ink Bottle (empty)",
    "Scribe’s Knife"
]