food_list = [
    "Beer",
    "Barley grain, good for soup with herbs",
    "Dried corn, ground and made into porrige",
    "Dried beans",
    "Dried berries",
    "Fruit leather",
    "Dried grain",
    "Dried mystery meat",
    "Dried beef",
    "Salted pork",
    "Bacon",
    "Smoked fish",
    "Dried fish",
    "Salted fish",
    "Crackers",
    "Dried Bread",
    "Pickled eggs",
    "Pickled onions",
    "Dried tubers",
    "Pickled herrings",
    "Pickled cabbage",
    "Mustard pickles",
    "Pickled cucumbers",
    "Waxed wheel of cheese",
    "Candied fruit",
    "Sheep cheese in oil",
    "Dried nuts",
    "Dried shrimp",
    "Pickled snails",
    "Dried mixed vegetables",
    "Dried Tofu",
    "Dried bean curd",
    "Dried sausages",
    "Fermented beans (tempe)",
    "Salted cauliflower",
    "Salted turnips",
    "Smoked cheese",
    "Sundried fruit",
    "Smoked rabbit",
    "Smoked game bird",
    "Jellied meat sealed in fat (confit)",
    "Goose or duck fat",
    "Butter",
    "Dried mushrooms or fungus",
    "Salted frogs",
    "Jam",
    "Honeyed meat",
    "Jellied eels",
    "Jellied lampreys",
    "Blood sausage - mostly lard, blood",
    "Honeyed locusts",
    "Olives in oil",
    "Mixed vegetables in oil",
    "Worms in aspic",
    "Dried squid",
    "Pickled mushrooms",
    "Fermented shrimp",
    "Fungus covered soft cheese",
    "Dried seaweed",
    "Truffles in oil",
    "Peppers in oil",
    "Pickled ant eggs",
    "Crickets in brine",
    "Century eggs",
    "Pickled Pumpkin",
    "Pickled chicken feet",
    "Pate sealed in fat",
    "Sheeps head cheese (not cheese at all)",
    "Jellied calf head and feet",
    "Pickled brains",
    "Jugged hare",
    "Fermented milk (alcoholic)",
    "Fermented fish heads",
    "Lutefisk (fish treated with lye)",
    "Pickled sea urchins",
    "Dried jellyfish",
    "Acorn flour",
    "Chestnut paste",
    "Pickled baby mice",
    "Dried crickets",
    "Fermented pork and rice",
    "Pickled fish eyes",
    "Seabirds in seal fat",
    "Salted whale blubber",
    "Pickled starfish",
    "Dried scorpion",
    "Snake pickled in wine",
    "Kunga cake, pressed block of flies",
    "Dried or pickled centipedes",
    "Dried mosquito eggs",
    "Dried Lizard",
    "Dried Rat",
    "Jellied elk nose",
    "Wine often made from non grapes lie dandylion",
    "Prunes in poert",
    "Kumquats in brandy",
    "Rhubarb preserve",
    "Apple and blackberry preserve",
    "Cider",
    "Mead"
]