inns_kitchen_items = [
    "Herbs (Roll once on the Spices and Herbs Table)",
    "Chicken eggs (24)",
    "Candles (2)",
    "Beef (side)",
    "Butter (1/2lbs)",
    "Milk (3 gallons)",
    "Spit",
    "Bacon (4lbs)",
    "Apples (2)",
    "Herbs (Roll twice on the Spices and Herbs Table)",
    "Spoon (Wooden)",
    "Fire poker",
    "Bellows",
    "Bread (half loaf)",
    "Pork (half side)",
    "Mice (1D20)",
    "Pot (Large)",
    "Pancake Batter (1lbs)",
    "Frying pan",
    "Cutting Board",
    "Wine Bottle (empty)",
    "Onions (6)",
    "Herbs (Roll three times on the Spices and Herbs Table)",
    "Rabbit meat (6)",
    "Mortar and Pestle",
    "Plates (6 wooden)",
    "Plum Pie",
    "Flatware (6 sets)",
    "Cheese Wheel (1/2)",
    "Copper Pieces (1D20)",
    "Spoon (metal)",
    "Firewood (1D20 log)",
    "An Old Cook Stokes a Fire",
    "Cauldron (empty)",
    "Bread (1 loaf)",
    "Wine bottle (half full)",
    "Herbs (Roll six times on the Spices and Herbs Table)",
    "Hot coals",
    "Cheese Wheel (2)",
    "Apples (4)",
    "Bowl (metal)",
    "Knife",
    "Turn Spit Dog",
    "Milk (1 gallon)",
    "Lantern",
    "Venison (side)",
    "Bag of Coal (120lbs)",
    "Pancake Batter (3lbs)",
    "Incriminating Letter",
    "Candles (6)",
    "Butter (1lbs)",
    "Kindling (1D20)",
    "Wine bottle (full)",
    "Plates (8 ceramic)",
    "Herbs (Roll eight times on the Spices and Herbs Table)",
    "Stew (10 bowls)",
    "Ham (raw)",
    "Cheese cloth",
    "A Serving Girl Gathers Dishes",
    "Apples (6)",
    "Chicken Eggs (12)",
    "Copper Pieces (1D10)",
    "Bread (4 loaves)",
    "Bowl (Wooden)",
    "Milk (2 gallons)",
    "Butter (4lbs)",
    "Rats (1D20)",
    "An Old Woman Stirs a Pot",
    "Bacon (10lbs)",
    "Cheese Wheel (1)",
    "Rolling Pin",
    "Love Letter",
    "Bag of Charcoal (100lbs)",
    "Secret Door (ceiling)",
    "Venison (half side)",
    "Bread knife",
    "Meat Cleaver",
    "Bread (6 loaves)",
    "Butter (2lbs)",
    "Mutton (side)",
    "Biscuits (50 freshly baked)",
    "Onions (12)",
    "Secret Door (floor)",
    "Apples (8)",
    "Pie Weights (3)",
    "Chicken eggs (36)",
    "Map to a Dungeon",
    "Flatware (10 sets)",
    "Sharpening stone",
    "Small Wooden Box (locked)",
    "Pork (side)",
    "Cheese Cutter",
    "Copper Pieces (3D20)",
    "Cheese Wheels (6)",
    "Apples (10)",
    "Herbs (Roll ten times on the Spices and Herbs Table)",
    "Bread (10 loaves)",
    "Milk (5 gallons)",
    "Apples (12)",
    "Ham (baked)"
]