interesting_trinkets_items = [
    "A shining pendant of white stone, engraved with a symbol that you vaguely recognize.",
    "An ivory chess piece that once belonged to an Elven king. An adventuring ancestor of yours stole it and it has been passed down for many generations.",
    "A quill pen crafted from the feather of a griffon. The feather can change the color of the ink being used on command.",
    "A faded flag that belonged to a mysterious sea vessel. The ship was never found and you came across the flag washed ashore on the beach.",
    "A troll's fang hanging from a leather cord. The troll was slain by a local folk hero and given to you as a gift.",
    "The signet ring of a vanished monarchy.",
    "Skull of a creature that nobody can recognize. It resembles a large bird with a hollow bone tube protruding from its forehead.",
    "A large and curious-looking bulb (botanical). Nobody knows what will grow if it's planted.",
    "A jar of unrecognizable spicy sauce that is from a foreign land.",
    "A set of four bone dice, so worn that you can barely make out the symbols.",
    "A silver ring with a small hidden compartment.",
    "A fist sized glass eye.",
    "An old music box that plays a vaguely recognizable song nobody can place.",
    "A pocket-size photo that can blink.",
    "A worn-out book of jokes your grandpa use to win your grandma. It's dedicated to you even if you didn't meet him.",
    "A tiny dragon preserved in amber.",
    "A river stone that crumbles when you hold it, but never gets smaller.",
    "A mouse skull that floats when placed over a fire",
    "A small tooth with a romantic scene carved into it in the finest detail.",
    "A gem that projects an illusion of a girl in white, she seems to be asking for something.",
    "A stamp for a wax seal of a design you’ve never seen before.",
    "A matchstick with a statue carved out of the head.",
    "A bottle of wine with a label dated from before the Spellplague.",
    "A medal known to be awarded to heroes of a long forgotten kingdom.",
    "An unsigned contract with an otherworldly entity that grants the undersigned a favor at the cost of one returned, any time any where any how.",
    "A flower of unknown species that grows in an empty vase in a darkened room - no soil no water no light.",
    "An engraved dagger that supposedly belonged to an adventuring family member.",
    "A dark amulet found in a relative's desk/dresser drawer.",
    "A piece of paper with the names of your present or future party members on it.",
    "A mummified finger that crawls like an inch worm.",
    "A small mirror that reflects how you might look in ten years time.",
    "A tiny bell that sprinkles fine glitter when rung.",
    "A intricately chased pommel that must have come from a very special sword.",
    "A coin that always lands on its edge when tossed/dropped.",
    "A trio of interlinked rings, which rotate slowly when put on a flat surface.",
    "A vial with a liquid inside that never comes full to rest.",
    "A rectangle of brass with cutouts and notches at regular intervals.",
    "A tin box with a small, eternally lit ember inside.",
    "A ring of dozens of keys, with no two matching.",
    "An ancient animal femur, smooth and brown, with a silvered head.",
    "A pearl earring that occasionally produces a mild electric shock.",
    "A silvered horseshoe that points towards strong sources of magic.",
    "An onyx astrolabe, also usable as a spell focus for the astrologically-inclined.",
    "The skull of a doppelganger carved into a mask. Sometimes it still shifts and takes new shapes.",
    "A silver pin in the shape of a lily with a blue gem set at its heart.",
    "An ornately carved wooden ink pen that improves your handwriting.",
    "A twisted stone ring with seemingly only one edge if you trace it with your finger. Grants the wearer pleasant dreams.",
    "An old weathered stone that glitters in the firelight.",
    "A small leather coin pouch that looks as if it can only carry one coin - a lucky coin.",
    "A well worn copper coin with a hole in it, threaded on a cord. You always feel warm wearing it.",
    "A small wooden lock box. The interior has a spot carved for an object, but the object is missing.",
    "A pitcher in the shape of a cat that pours cream no matter what liquid is inside.",
    "A stone carved in the shape of a squat frog. Whatever surface it is placed on becomes damp.",
    "A miniature carved stone wizards tower, no longer than your hand. At night, the window at the top glows with a pleasant light.",
    "An cold-iron nail twisted into the shape of a holy symbol.",
    "A set of jadeite bangles with silver clasps, meant to be worn on the wrist.",
    "A small, perfectly round crystal sphere, with a strangely shaped gold piece embedded in the center. The coin is from a distant and ancient kingdom.",
    "A chain of rose gold and nine tiny rose gold bells in the shape of acorns.",
    "A tiny, carved, rock crystal swan.",
    "A two sided red and white chalcedony cameo necklace, banded with gold. The carving is of a pastoral scene on one side, and a snarling beast on the other.",
    "A necklace of gold braid and nine knots, with an ivory clasp.",
    "Brass toy cart with a removeable little brass hedgehog rider, pulled by a brass rooster. The cart is decorated with a noble family crest.",
    "A dusty pink rose quartzite prism deeply etched with monogrammed initials.",
    "A gold and azurite brooch in the shape of a knotted branch and berries.",
    "A carved stone horned toad made of Labradorite weighing approximately 2 kilograms. The toad is comprised of four pieces and fit together like a jigsaw.",
    "A scrap of folded paper containing a message. Every time it is folded and unfolded the message changes.",
    "A pocket watch that won’t stop spinning.",
    "A glass lens that makes the world appear black and white when looked through.",
    "A jar with an eyeball floating inside that occasionally moves.",
    "A solid sphere of ice that emits smoke but cannot melt.",
    "A glove made of writhing vines.",
    "A copper, hexagonal coin. On one side is a smiling face and the words “remember to live”. On the other is a skull and the words “remember you will die”.",
    "A platinum hatpin with an image of a sailing ship.",
    "A brass disk divided by a 23 pointed star, and inset 7 small glass beads around the edge, with a series of small gauged holes and notches drilled in the disk. They are astonishingly precise, and are a wonder of manufacturing skill and machined tolerances.",
    "A tiny wooden box with a hollow globe of crystal filled with quicksilver and a fine-sized crystal glass boat and boatman inside it. The boatman occasionally changes poses, and sometimes catches little crystal fish.",
    "A compact, rugged brass clock in a small travelling case, which tells the time accurately and never loses a minute so long as it is carefully wound each day. It accurately records the phases of the moon, as well as local noon, sunrise, sunset, star-rise, and local midnight.",
    "A rectangle of cloudy white crystal, edged with silver. Looking through it will always show the position of the sun on a cloudy day.",
    "A complete deck of antique playing cards that once belonged to a royal family. The face of one of the queens has been scribbled out.",
    "A fine-toothed comb carved from a beautiful seashell and inlaid with silver.",
    "A small bunch of grapes carved from a dark red crystal. Licking them or placing them in your mouth will give you the flavor of grapes, but no sustenance.",
    "A curiously made coin of magically toughened glass, stamped with obscure ritual imagery and filled with quicksilver, without seams or air bubbles. They are about 20% larger than the size of a standard gold coin, but five times thicker and weighing 5 times as much as a single coin (10 per pound). To a numismatist collector it may be worth anywhere from 30 to 150gp. It contains 30gp worth of quicksilver.",
    "A polished looking-glass made from a thin-slab of pyrite the size of one's hand. The back is etched with a sort of symbolic nonsense that resists decipherment. It weighs 4 pounds.",
    "A heavy brass tube two feet long, and an inch across, in the shape of a stylized dragon's head and mouth.",
    "An small statue of an animal, with a mouthpiece or whistle, and all made from terra-cotta pottery. When one blows through the end, the statue sounds authentically like the animal it looks like.",
    "A small crystal ball filled with smoke. The smoke changes color to reflect the weather in a specific location.",
    "A scrap of parchment outlining the solution to a puzzle.",
    "A broach made from a large opal and the bones of giant insects.",
    "A clear gem on a chain, that gradually changes color when exposed to different schools of magic.",
    "A bracelet of silver beads. If a bead is separated from the bracelet, it will always roll in the direction of the wearer.",
    "A whistle that attracts small mammalian creatures when blown.",
    "A miniature trident, with fey patterns inscribed on it.",
    "A small porcelain frog, which releases a little spray of water if stroked along its back.",
    "A platinum gambling chip, with a small crescent piece carved out of the center.",
    "A smooth reddish river stone, with veins of quartz and gold running through it.",
    "A tiny book made of exquisite porcelain reliefs.",
    "A clockwork caterpillar that walks in ever widening spirals.",
    "A functional small scale model of a cannon.",
    "A set of bone dice in a leather and velvet case. The dice bear runes instead of numbers.",
    "A metal apple with individual segments made of lead, tin, copper, bronze, iron, silver, gold and platinum.",
    "A nose to chin mask, which forces the wearer to talk in whispers."
]