nobles_bechamber_items = [
    "Family sword",
    "Sapphire ring",
    "Chamber pot",
    "Family Crest",
    "Suit of Armor",
    "Portrait of Ancestor",
    "Signet ring",
    "Ornate chest",
    "Large wardrobe",
    "Emerald ring",
    "Locked door",
    "Mounted fish",
    "Stuffed Minotaur",
    "Inkwell",
    "Lavish chair",
    "Combination to safe",
    "Self portrait",
    "Undergarments",
    "Silk pantaloons",
    "Silver Urn",
    "Painting of noble lineage",
    "Map of local area",
    "Shelf of hunting trophies",
    "Noble’s Journal",
    "Gold statuette",
    "Decorative Axe",
    "Large Ruby",
    "Stuffed falcon",
    "Bundle of love letters",
    "Platter of exotic fruits",
    "Small safe",
    "Silver bathtub",
    "Burning letters",
    "Large bed with curtains",
    "Family Shield",
    "Painting of noble’s home",
    "Diamond ring",
    "Painting of beautiful woman",
    "Gold urn",
    "Stuffed wolf",
    "Large Emerald",
    "Gold trimmed desk",
    "Leather bindings",
    "Unopened letter",
    "Silver trimmed robes",
    "Model ship",
    "Gold trimmed fan",
    "Exquisite rug",
    "Painting easel",
    "Mortar and pestle",
    "Gold animal skull",
    "Silver trimmed fan",
    "Bottle of rare liquor",
    "Coin purse",
    "Silver Locket",
    "Decorative armor",
    "Family axe",
    "Scepter",
    "Silver rose",
    "Bookshelf of family lineage",
    "Ancestor’s spear",
    "Exquisite vase",
    "Statue of noble",
    "Pearl necklace",
    "Gold bathtub",
    "Confiscated journal",
    "Painting of dragon",
    "Gold lion statuette",
    "Shrine to a God",
    "Map of neighboring city",
    "List of “rivals”",
    "Plan to usurp",
    "Large sapphire",
    "Ruby ring",
    "Gold locket",
    "Embroidered pajamas",
    "Expensive wine",
    "Golden rose",
    "Wedding attire",
    "Gold trimmed clothing",
    "Decorative sword",
    "Hidden Vault",
    "Mounted deer head",
    "Alchemical notes",
    "Enchanted ring",
    "Slippers",
    "Door to balcony",
    "Caged falcon",
    "Hunting bow",
    "Golden dragon skull (ruby eyes)",
    "Statue of ancestor",
    "Jewelry chest",
    "Large safe",
    "Discarded clothing",
    "Ancestral Sword",
    "Shrine to ancestors",
    "Key to vault",
    "Assassin",
    "Silver dragon skull (sapphire eyes)",
    "Noble’s corpse"
]