port_masters_office_items = [
    "Shipping Manifesto",
    "Maps of Surrounding Seas",
    "Inkwell (dry)",
    "Bowl of Fish Eggs",
    "Decorative Helm",
    "List of Ships Arriving Today",
    "Warning Letter to Pirate Captain",
    "Fishing Rod",
    "Prayers to Sea God",
    "Candles (1d4)",
    "Mounted Shark",
    "Bounty Board",
    "Ship’s Flag",
    "Jeweled Seashell",
    "Sea Chest",
    "Legal Documents",
    "Port Master’s Seal",
    "Bottles Of Mead (1D8)",
    "Pewter Flagon (empty)",
    "Visitors Ledger",
    "Star Charts",
    "Calendar",
    "Decorative Oar",
    "The Art of Sea Navigation (book)",
    "Fiddle",
    "Fancy Lockbox",
    "Ferry Schedules",
    "List of Local Ships",
    "Port Master’s Journal",
    "Keys (1D12)",
    "Quills (1D4)",
    "Model Ship",
    "Sextant",
    "Antique Sword",
    "Small Vault",
    "Mounted Crab",
    "Tax Records",
    "Map of Shipping Route",
    "Old Shipping Records",
    "Warehouse Inventory Log",
    "Wax (5 cubes)",
    "Symbol of Sea God",
    "Rusted Lockbox",
    "Pipe Tobacco",
    "Bucket of Seashells",
    "Inkwell",
    "Conch Shell",
    "Help Wanted Ad",
    "Compass",
    "Donation Box for Families of Lost Sailors",
    "Map Of Town (Plastered On Wall)",
    "Illustration of Legendary Ship",
    "Collection of Beautiful Seashells",
    "List of Common Sea Laws",
    "Single Key",
    "Bookshelves (1D100 books)",
    "Mounted Swordfish",
    "Lamp Oil (2 flasks)",
    "Rum (1D12 bottles)",
    "Bundle of Letters",
    "Antique Fishing Gear",
    "Memorial Plaque to Lost Sailors",
    "Jar Of Marbles",
    "Stuffed Squid",
    "Jar Of Pickled Fish",
    "Ship In Bottle",
    "Antique Anchor",
    "Map of the Port and Related Areas",
    "Financial Reports",
    "Trading Company Contract",
    "A Letter to the Cooper",
    "Dagger",
    "Weatherworn Captain’s Cloak",
    "Old Captain’s Journal",
    "Wanted Posters Marked “Collected”",
    "Pirate Flag",
    "Straight Razor",
    "Dried Rations (1D4)",
    "Spyglass",
    "Manual on Knot Tying",
    "Treasure Map",
    "Gold Pieces (1D20)",
    "Short Sword",
    "Coat Of Arms",
    "Weird Symbols Scratched on Wall",
    "Book of Sea Shanties",
    "Bill of Sale for a Ship",
    "Rabbit’s Foot",
    "Alter to Sea God",
    "Dragon Skull",
    "Strange Creatures of the Deep (book)",
    "Silver Pieces (1D100)",
    "List of Port Rules",
    "Pouch Filled with Shark’s Teeth",
    "Hourglass",
    "Preserved Tentacle (35ft)",
    "Vellum (1d12 sheets)",
    "Mystical Seashell",
    "Skull of Pirate",
    "Egg (decorative, 2ft tall)"
]