weapons_armor_and_equipment_items = [
    "Clothes, common",
    "Maul",
    "Chain Shirt",
    "Tinderbox",
    "Lantern, hooded",
    "Blowgun Needles (50)",
    "Crossbow, hand",
    "Hourglass",
    "Spyglass",
    "Pick, miner’s",
    "Blanket",
    "Pike",
    "Shortbow",
    "Chain Mail",
    "Warhammer",
    "Candle",
    "Arrows (20)",
    "Longbow",
    "Alchemist’s fire (flask)",
    "Scimitar",
    "Soap",
    "Waterskin",
    "War Pick",
    "Rope, hempen (50 feet)",
    "Tent, two-person",
    "Leather Armor",
    "Manacles",
    "Backpack",
    "Trident",
    "Grappling hook",
    "Splint Armor",
    "Breastplate",
    "Dagger",
    "Ring Mail",
    "Poison, basic (vial)",
    "Quiver",
    "Shovel",
    "Halberd",
    "Javelin",
    "Longsword",
    "Flail",
    "Rapier",
    "Fishing tackle",
    "Lantern, bullseye",
    "Blowgun",
    "Glaive",
    "Hammer",
    "Vial",
    "Crossbow, heavy",
    "Greataxe",
    "Pouch",
    "Case, crossbow bolt",
    "Net",
    "Rope, silk (50 feet)",
    "Oil (flask)",
    "Crowbar",
    "Rations (1 day)",
    "Handaxe",
    "Battleaxe",
    "Greatsword",
    "Spikes, iron (10)",
    "Piton",
    "Spear",
    "Sling",
    "Hide Armor",
    "Lance",
    "Torch",
    "Robes",
    "Magnifying glass",
    "Whetstone",
    "Studded Leather Armor",
    "Pole (10-foot)",
    "Shield",
    "Shortsword",
    "Club",
    "Ball bearings (bag of 1,000)",
    "Morningstar",
    "Caltrops (bag of 20)",
    "Chalk (1 piece)",
    "Clothes, traveler’s",
    "Greatclub",
    "Sickle",
    "Mace",
    "Crossbow, light",
    "Dart",
    "Plate Armor",
    "Sling bullets (20)",
    "Whip",
    "Light Hammer",
    "Crossbow bolts (20)",
    "Hunting trap",
    "Half Plate Armor",
    "Holy Water (flask)",
    "Bedroll",
    "Hammer, sledge",
    "Quarterstaff",
    "Case, map or scroll",
    "Chain (10 feet)",
    "Scale Mail",
    "Padded Armor"
]